# Naive RAG

**[Knowledge base building process]**  
- Step1. Data Load(Document Loader)  
- Step2. Chunking(Text Splitter)  
- Step3. Vectorizing(Embedding)  
- Step4. Vector DB storage  

**[Runtime process]**  
- Step1. Query vectorization  
- Step2. Retrieval  
- Step3. LLM request (RAG Chain 구성)  
- Step4. 답변 출력  

[Data]  
- 저작권 판례 Data set

[Note]
- Advanced RAG Techniques를 더해 응답 품질을 개선함
- KB는 판례 + QA(평가 holdout 제외)로 구성
- 평가에는 QA holdout만 사용하므로, 평가 질문 원문 자체는 KB에 들어가지 않음
- retrieval 단계에서는 QA 문서에 보너스를 주고, 최종 context는 `판례 3개 + QA 2개` 우선 혼합으로 구성
- 목표: `factual_correctness` 를 높이면서 판례 근거를 함께 유지

In [1]:
%pip install -q langchain langchain-openai langchain-community langchain-chroma chromadb ragas

Note: you may need to restart the kernel to use updated packages.

In [ ]:
import os

# Open AI API Key
os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY", "")

In [3]:
# Local workspace path
from pathlib import Path

PROJECT_ROOT = Path.cwd().resolve()
DATASET_PATH = PROJECT_ROOT / "저작권판례데이터셋"
CHROMA_PATH = PROJECT_ROOT / "chroma_db"
CHROMA_PATH.mkdir(exist_ok=True)

print("현재 작업 경로:", PROJECT_ROOT)
print("데이터셋 경로:", DATASET_PATH)
print("ChromaDB 저장 경로:", CHROMA_PATH)

현재 작업 경로: /Users/hjcha/Documents/NavieRAG실습
데이터셋 경로: /Users/hjcha/Documents/NavieRAG실습/저작권판례데이터셋
ChromaDB 저장 경로: /Users/hjcha/Documents/NavieRAG실습/chroma_db

## Knowledge Base 구축: Step1. Data Load(Document Loader)

In [4]:
import pandas as pd
from langchain_core.documents import Document

case_raw_docs = []
qa_raw_docs = []

QA_EVAL_HOLDOUT_SIZE = 10
qa_full_df = pd.read_excel(DATASET_PATH / "Copyright_QA_GroundTrue.xlsx").dropna(subset=["Q", "A"]).reset_index(drop=True)
qa_kb_df = qa_full_df.iloc[:-QA_EVAL_HOLDOUT_SIZE].copy()
qa_eval_df = qa_full_df.iloc[-QA_EVAL_HOLDOUT_SIZE:].copy()
case_df = pd.read_excel(DATASET_PATH / "Copyright_case_law_Supreme.xlsx").dropna(subset=["판례내용"]).reset_index(drop=True)
kb_case_df = case_df.copy()

print(f"KB 판례 수: {len(kb_case_df)}")
print(f"Hybrid KB용 QA 수: {len(qa_kb_df)}")
print(f"평가용 QA holdout 수: {len(qa_eval_df)}")

KB 판례 수: 423
Hybrid KB용 QA 수: 21
평가용 QA holdout 수: 10

In [5]:
print("Evaluation QA holdout sample")
print("-----------------------------")
print(qa_eval_df[["Q", "A"]].head(3))

Evaluation QA holdout sample
-----------------------------
                                            Q  \
21      연예인의 이름을 상업적 행위에 이용할 경우, 손해배상책임을 지나요?
22  다른 사람이 나의 저작물을 패러디하였는데 저작권 침해에 해당하는 것일까요?
23  사진이나 영상에 연예인의 유행어를 이용하는 것도 침해에 해당하는 것일까요?

                                                    A
21  유명 연예인이나 운동선수 등은 자신의 성명이나 초상을 상업적으로 이용할 수 있는 권...
22  저작권법상 허용되는 패러디에 대한 판단 기준이 명확하지는 않으나, 기존의 저작물에 ...
23  짧은 유행어를 이용하는 경우는 저작권 침해로 보기는 어렵지만 퍼블리시티권 침해에 해...

In [6]:
import logging
import re
from collections import OrderedDict

logger = logging.getLogger("rag_notebook")
if not logger.handlers:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")

logging.getLogger("openai").setLevel(logging.WARNING)
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("httpcore").setLevel(logging.WARNING)

ARTICLE_PATTERN = re.compile(r"제\s*(\d+(?:의\d+)?)\s*조")
HO_PATTERN = re.compile(r"제\s*(\d+(?:의\d+)?)\s*항")

def normalize_legal_number(value: str) -> str:
    return str(value).replace(" ", "")

def extract_article_metadata(text: str) -> list[str]:
    return list(OrderedDict.fromkeys(normalize_legal_number(match) for match in ARTICLE_PATTERN.findall(text)))

def extract_ho_metadata(text: str) -> list[str]:
    return list(OrderedDict.fromkeys(normalize_legal_number(match) for match in HO_PATTERN.findall(text)))

def extract_query_article(question: str) -> str | None:
    match = ARTICLE_PATTERN.search(question)
    return normalize_legal_number(match.group(1)) if match else None

def clean_case_text(text: str) -> str:

    if text is None:
        return ""

    if "【이 유】" in text:
        text = text.split("【이 유】", 1)[1]

    text = re.split(r"【참조조문】", text)[0]
    text = re.split(r"【참조판례】", text)[0]
    text = re.sub(r"\n\s*\n", "\n", text)

    return text.strip()

In [7]:
# Case law dataset for knowledge base
for _, row in kb_case_df.iterrows():
    raw_text = str(row.get("판례내용", ""))
    cleaned_text = clean_case_text(raw_text)
    article_metadata = extract_article_metadata(cleaned_text)
    ho_metadata = extract_ho_metadata(cleaned_text)

    content = f"""
사건명: {row['사건명']}
법원: {row['법원명']}
선고일: {row['선고일자']}
사건번호: {row['사건번호']}

판례내용:
{cleaned_text}
"""

    case_raw_docs.append(
        Document(
            page_content=content,
            metadata={
                "document_type": "case_law",
                "case_number": str(row["사건번호"]).strip(),
                "court": str(row["법원명"]).strip(),
                "date": str(row["선고일자"]).strip(),
                "article": article_metadata,
                "ho": ho_metadata,
                "article_count": len(article_metadata),
            }
        )
    )

for idx, row in qa_kb_df.iterrows():
    combined_text = f"질문: {row['Q']}\n답변: {row['A']}"
    qa_raw_docs.append(
        Document(
            page_content=combined_text,
            metadata={
                "document_type": "qa",
                "case_number": f"QA-{idx}",
                "court": "QnA",
                "date": "N/A",
                "article": extract_article_metadata(combined_text),
                "ho": extract_ho_metadata(combined_text),
                "article_count": len(extract_article_metadata(combined_text)),
            }
        )
    )

print("Case KB documents:", len(case_raw_docs))
print("QA KB documents:", len(qa_raw_docs))
print("Case sample metadata:", case_raw_docs[-1].metadata)

Case KB documents: 423
QA KB documents: 21
Case sample metadata: {'document_type': 'case_law', 'case_number': '2003도7572', 'court': '대법원', 'date': '2004.07.22', 'article': ['4', '2'], 'ho': ['1'], 'article_count': 2}

In [8]:
print("Case law dataset")
print("-----------------------------")
print(f"[page_content]\n{case_raw_docs[0].page_content}")
print(f"\n[metadata]\n{case_raw_docs[0].metadata}")

Case law dataset
-----------------------------
[page_content]

사건명: 도메인이름 이전청구권 부존재확인, 손해배상(지)
법원: 대법원
선고일: 2022.04.14
사건번호: 2021다303134(본소),

판례내용:
【주 문】
 상고를 기각한다.
 상고비용은 원고(반소피고)가 부담한다.
 이유
 상고이유(상고이유서 제출기간이 지난 뒤에 제출된 참고서면의 기재는 이를 보충하는 범위에서)를 판단한다.
 1. 저작권 침해의 방조 관련 상고이유에 대한 판단
 가. 저작재산권자는 다른 사람에게 그 저작물의 이용을 허락할 수 있고, 그 이용을 허락 받은 자는 허락받은 이용 방법 및 조건의 범위 안에서 그 저작물을 이용할 수 있다. 또한 위 허락에 의하여 저작물을 이용할 수 있는 권리는 저작재산권자의 동의 없이 제3자에게 이를 양도할 수 없다(
 저작권법 제46조
 ). 따라서 저작권자로부터 저작물의 이용을 허락받지 못한 사람은 저작물을 복제 또는 사용할 수 없고, 저작물의 이용을 허락받은 사람도 허락받은 이용 방법 및 조건의 범위 안에서 그 저작물을 이용 · 양도할 수 있을 뿐이다.
 컴퓨터 프로그램 또는 그 라이선스의 판매 시 함께 제공되는 일련번호와 같은 제품키는 컴퓨터 프로그램을 설치 또는 사용할 권한이 있는가를 확인하는 수단인 기술적 보호조치로서, 누군가가 프로그램을 복제하고 그 복제행위가 컴퓨터 프로그램 저작권을 침해하는 행위에 해당한다면 이를 용이하게 하는 제품키의 복제 또는 배포행위는 위와 같은 행위를 용이하게 하는 행위로서 경우에 따라 프로그램 저작권 침해행위의 방조에 해당할 수 있다(
 대법원 2002. 6. 28. 선고 2001도2900 판결
 참조).
 나. 원심은 판시와 같은 이유를 들어 다음과 같이 판단하였다. ① 사용자가 별도의 라이선스 구입 없이 원고로부터 제품키만을 구입하여, 피고 사이트로부터 Windows 10Pro 또는 Home 프로그램을 다운로드 받으며 그 과정에서 제시되는 'Windows 운영체제에 관한 피고 소프트웨어 사용권 계약'에 동의하고 위 제품키로 인증받아 사용하는 행위는 위 사용권 계약에 따라 허용되지 않는다. 따라서 사용자가 위와 같이 이 사건 프로그램을 다운받아 복제하는 행위는 저작권 침해행위에 해당하고, 제품키를 판매한 원고의 행위는 저작권 침해행위의 방조에 해당한다. ② 위 사용권 계약에서 정한 이 사건 프로그램 양도 조건을 충족하지 않는 한 원고로부터 이미 사용된 제품키를 구입하여 새롭게 이 사건 프로그램을 다운받아 인증한 것만으로 라이선스가 이전된다고 볼 수 없다.
 다. 앞서 본 법리 및 기록에 의하면 이러한 원심판단은 정당하고, 거기에 상고이유 주장과 같이 필요한 심리를 다하지 아니하고 논리와 경험의 법칙을 위반하여 자유심증주의의 한계를 벗어나거나, 제품키의 양도가능성 및 관련 계약의 해석, 복제권 침해와 라이선스 계약 위반의 구별, 라이선스 양도 조건 관련 계약의 해석에 관한 법리를 오해하여 판결에 영향을 미친 잘못이 없다.
 2. 도메인이름 이전등록 관련 상고이유에 대한 판단
 원심은 판시와 같은 이유로 피고는 원고가 사용 중인 도메인이름 'window10.asia'(이하 '이 사건 도메인이름'이라고 한다)와 동일 또는 유사한 'Windows' 및 'Windows 10'표지에 대하여 정당한 권원이 있고, 원고는 부정한 목적으로 이 사건 도메인이름을 등록 · 보유 ·사용하고 있으므로, 원고는 피고에게 이 사건 도메인이름에 관하여 이전등록절차를 이행할 의무가 있다고 판단하였다.
 관련 법리와 기록에 의하면 이러한 원심판단은 정당하고, 거기에 필요한 심리를 다하지 아니하고 논리와 경험의 법칙을 위반하여 자유심증주의의 한계를 벗어나거나,
 인터넷주소자원에 관한 법률 제12조
 의 부정한 목적의 판단기준, 도메인이름 사용자의 정당한 이익 등 도메인이름 이전등록청구와 관련한 법리를 오해하여 판결에 영향을 미친 잘못이 없다.
 3. 결론
 그러므로 상고를 기각하고 상고비용은 패소자가 부담하도록 하여, 관여 대법관의 일치된 의견으로 주문과 같이 판결한다.


[metadata]
{'document_type': 'case_law', 'case_number': '2021다303134(본소),', 'court': '대법원', 'date': '2022.04.14', 'article': ['46', '12'], 'ho': [], 'article_count': 2}

## Knowledge Base 구축: Step2. Chunking(Text Splitter)

In [9]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    separators=["\n\n", "【", "판례내용:", "\n"],
)

case_docs = splitter.split_documents(case_raw_docs)
qa_docs = splitter.split_documents(qa_raw_docs)
docs_by_mode = {
    "case_only": case_docs,
    "case_plus_qa": case_docs + qa_docs,
}

docs = docs_by_mode["case_only"]

print(f"Case-only chunk count: {len(case_docs)}")
print(f"Case+QA chunk count: {len(docs_by_mode['case_plus_qa'])}")
print("\nChunk Samples\n")
for i, d in enumerate(case_docs[:5]):
    print(f"[Chunk {i}] ({len(d.page_content)} chars)")
    print(d.page_content[:100], "...\n")

/opt/homebrew/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Case-only chunk count: 1543
Case+QA chunk count: 1578

Chunk Samples

[Chunk 0] (78 chars)
사건명: 도메인이름 이전청구권 부존재확인, 손해배상(지)
법원: 대법원
선고일: 2022.04.14
사건번호: 2021다303134(본소), ...

[Chunk 1] (5 chars)
판례내용: ...

[Chunk 2] (708 chars)
【주 문】
 상고를 기각한다.
 상고비용은 원고(반소피고)가 부담한다.
 이유
 상고이유(상고이유서 제출기간이 지난 뒤에 제출된 참고서면의 기재는 이를 보충하는 범위에서)를 판단한 ...

[Chunk 3] (931 chars)
대법원 2002. 6. 28. 선고 2001도2900 판결
 참조).
 나. 원심은 판시와 같은 이유를 들어 다음과 같이 판단하였다. ① 사용자가 별도의 라이선스 구입 없이 원고로 ...

[Chunk 4] (264 chars)
관련 법리와 기록에 의하면 이러한 원심판단은 정당하고, 거기에 필요한 심리를 다하지 아니하고 논리와 경험의 법칙을 위반하여 자유심증주의의 한계를 벗어나거나,
 인터넷주소자원에 관한 ...

## Knowledge Base 구축: Step3. Vectorizing(Embedding)

- 개념적으로는 두 단계이지만, Embedding + VectorDB 저장은 한번에 처리됨
- text-embedding-3-large은 3072차원

In [10]:
from langchain_openai import OpenAIEmbeddings
import numpy as np

embedding_model = OpenAIEmbeddings(model="text-embedding-3-small")

sample_vector = embedding_model.embed_query("저작권 침해 판단 기준은?")
print(f"임베딩 차원수: {len(sample_vector)}")
print(f"벡터 앞 5개 값: {sample_vector[:5]}")

임베딩 차원수: 1536
벡터 앞 5개 값: [0.04510498046875, 0.050262451171875, 0.03668212890625, 0.0011882781982421875, 0.032440185546875]

## Knowledge Base 구축: Step4. Vector DB storage

In [11]:
# ChromaDB 저장을 위한 Path 설정
COLLECTION_NAMES = {
    "case_only": "copyright_rag_case_only",
    "case_plus_qa": "copyright_rag_case_plus_qa",
}
ACTIVE_MODE = "case_plus_qa"
print(f"ChromaDB 저장 경로: {CHROMA_PATH}")
print(f"활성 모드: {ACTIVE_MODE}")
print(f"컬렉션 이름: {COLLECTION_NAMES}")

ChromaDB 저장 경로: /Users/hjcha/Documents/NavieRAG실습/chroma_db
활성 모드: case_plus_qa
컬렉션 이름: {'case_only': 'copyright_rag_case_only', 'case_plus_qa': 'copyright_rag_case_plus_qa'}

In [12]:
from langchain_chroma import Chroma

def normalize_docs_for_chroma(documents):
    cleaned = []
    for doc in documents:
        metadata = doc.metadata.copy()
        if "article" in metadata and not metadata["article"]:
            metadata["article"] = None
        if "ho" in metadata and not metadata["ho"]:
            metadata["ho"] = None
        cleaned.append(Document(page_content=doc.page_content, metadata=metadata))
    return cleaned

def build_vector_store(documents, collection_name):
    vectorstore = Chroma(
        persist_directory=CHROMA_PATH,
        embedding_function=embedding_model,
        collection_name=collection_name,
    )
    normalized_docs = normalize_docs_for_chroma(documents)
    current_count = vectorstore._collection.count()
    if current_count != len(normalized_docs):
        if current_count > 0:
            vectorstore.delete_collection()
            vectorstore = Chroma(
                persist_directory=CHROMA_PATH,
                embedding_function=embedding_model,
                collection_name=collection_name,
            )
        vectorstore.add_documents(normalized_docs)
    return vectorstore

vectorstores_by_mode = {
    mode: build_vector_store(mode_docs, COLLECTION_NAMES[mode])
    for mode, mode_docs in docs_by_mode.items()
}
vectorstore = vectorstores_by_mode[ACTIVE_MODE]

for mode, store in vectorstores_by_mode.items():
    print(f"{mode}: {store._collection.count()} vectors")

case_only: 1543 vectors
case_plus_qa: 1578 vectors

In [13]:
# 보관된 vector DB 불러오기
# vectorstore = Chroma(
#     persist_directory=CHROMA_PATH,
#     embedding_function=embedding_model,
#     collection_name="copyright_rag",
# )

## Runtime: 질문 후보군

In [14]:
questions = [
    "저작권 침해가 성립하기 위한 요건은 무엇인가?",
    "저작물의 실질적 유사성 판단 기준은 무엇인가?",
    "저작권 보호 대상이 되는 저작물의 요건은 무엇인가?",
    "저작권 침해 판단에서 아이디어와 표현의 구별 기준은 무엇인가?",
    "저작권 침해 소송에서 법원이 고려하는 판단 기준은 무엇인가?"
]

for i, q in enumerate(questions, 1):
    print(f"Q{i}. {q}")

Q1. 저작권 침해가 성립하기 위한 요건은 무엇인가?
Q2. 저작물의 실질적 유사성 판단 기준은 무엇인가?
Q3. 저작권 보호 대상이 되는 저작물의 요건은 무엇인가?
Q4. 저작권 침해 판단에서 아이디어와 표현의 구별 기준은 무엇인가?
Q5. 저작권 침해 소송에서 법원이 고려하는 판단 기준은 무엇인가?

## Runtime: Step1. Query vectorization
- 동일한 embedding model을 사용해야 함

In [15]:
query = questions[2]

query_vector = embedding_model.embed_query(query)

print(f"Query: {query}")
print(f"\nQuery Vector Dimension: {len(query_vector)}")
print(f"Query Vector: {[round(v, 4) for v in query_vector[:5]]}")

Query: 저작권 보호 대상이 되는 저작물의 요건은 무엇인가?

Query Vector Dimension: 1536
Query Vector: [0.0673, 0.0629, -0.016, 0.017, 0.0495]

## Runtime: Step2. Retrieval
 ### BM25 + Vector Retriever

In [16]:
%pip install rank_bm25

Requirement already satisfied: rank_bm25 in /opt/homebrew/lib/python3.11/site-packages (0.2.2)
Requirement already satisfied: numpy in /opt/homebrew/lib/python3.11/site-packages (from rank_bm25) (2.4.3)
Note: you may need to restart the kernel to use updated packages.

In [17]:
from langchain_community.retrievers import BM25Retriever

VECTOR_SEARCH_TOP_K = 20
BM25_SEARCH_TOP_K = 20
RERANK_TOP_K = 5
ENABLE_CONTEXT_DEDUP = False
DEDUP_SIMILARITY_THRESHOLD = 0.97
MAX_SEARCH_QUERIES = 2
SOFT_FILTER_BONUS = 0.15
QA_DOC_BONUS = 0.20
CASE_LAW_DOC_BONUS = 0.05
METADATA_PREFILTER_K = 8
RETRIEVAL_SAMPLE_SIZE = 5
FINAL_QA_DOCS = 2
FINAL_CASE_DOCS = 3

def build_bm25_retriever(corpus_documents):
    retriever = BM25Retriever.from_documents(corpus_documents)
    retriever.k = BM25_SEARCH_TOP_K
    return retriever

mode_resources = {
    mode: {
        "docs": mode_docs,
        "vectorstore": vectorstores_by_mode[mode],
        "bm25_retriever": build_bm25_retriever(mode_docs),
    }
    for mode, mode_docs in docs_by_mode.items()
}

logger.info(
    "Retrieval config | vector_top_k=%s | rerank_top_k=%s | dedup=%s | max_queries=%s",
    VECTOR_SEARCH_TOP_K,
    RERANK_TOP_K,
    ENABLE_CONTEXT_DEDUP,
    MAX_SEARCH_QUERIES,
)

print("Retrievers initialized for modes:", list(mode_resources.keys()))

INFO | Retrieval config | vector_top_k=20 | rerank_top_k=5 | dedup=False | max_queries=2

Retrievers initialized for modes: ['case_only', 'case_plus_qa']

In [18]:
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI

query_llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

multi_query_prompt = PromptTemplate(
    input_variables=["question"],
    template="""당신은 법률 검색 질의 확장기입니다.
사용자 질문에 대해 검색 품질이 높은 한국어 재작성 질의 1개만 생성하세요.

조건:
- 원문 질문과 의미가 동일해야 합니다.
- 조문 번호가 있으면 반드시 유지하세요.
- 불필요한 설명 없이 질의 한 줄만 출력하세요.

질문: {question}""",
)

llm_chain = multi_query_prompt | query_llm

def expand_queries(question: str) -> list[str]:
    generated = llm_chain.invoke({"question": question})

    if hasattr(generated, "content"):
        text = generated.content
    elif isinstance(generated, dict):
        text = generated.get("text") or generated.get("queries") or next(iter(generated.values()))
    else:
        text = str(generated)

    expanded_queries = [line.strip("- ").strip() for line in str(text).splitlines() if line.strip()]
    queries = list(OrderedDict.fromkeys([question, *expanded_queries]))
    return queries[:MAX_SEARCH_QUERIES]

queries = expand_queries(query)
print("\nExpanded Queries:")
for i, q in enumerate(queries, 1):
    print(f"{i}. {q}")

Expanded Queries:
1. 저작권 보호 대상이 되는 저작물의 요건은 무엇인가?
2. 저작권 보호 대상 저작물의 요건은 무엇인가?

In [19]:
def log_documents(title: str, documents, limit: int = 5):
    logger.info("%s | count=%s", title, len(documents))
    for idx, doc in enumerate(documents[:limit], 1):
        preview = doc.page_content[:160].replace("\n", " ")
        logger.info(
            "%s #%s | case=%s | type=%s | article=%s | preview=%s",
            title,
            idx,
            doc.metadata.get("case_number"),
            doc.metadata.get("document_type"),
            doc.metadata.get("article"),
            preview,
        )

def has_article_match(doc, article_number: str | None) -> bool:
    if not article_number:
        return False
    return article_number in (doc.metadata.get("article") or [])

def document_type_bonus(doc, mode_name: str) -> float:
    doc_type = doc.metadata.get("document_type")
    if mode_name == "case_plus_qa" and doc_type == "qa":
        return QA_DOC_BONUS
    if doc_type == "case_law":
        return CASE_LAW_DOC_BONUS
    return 0.0

def metadata_soft_score(doc, article_number: str | None):
    if not article_number:
        return 0.0
    return SOFT_FILTER_BONUS if has_article_match(doc, article_number) else 0.0

def collect_vector_candidates(search_query: str, article_number: str | None, mode_name: str):
    vectorstore = mode_resources[mode_name]["vectorstore"]
    base_docs = vectorstore.similarity_search(search_query, k=VECTOR_SEARCH_TOP_K)
    if not article_number:
        return base_docs
    expanded_docs = vectorstore.similarity_search(search_query, k=VECTOR_SEARCH_TOP_K * 2)
    prioritized_docs = [doc for doc in expanded_docs if has_article_match(doc, article_number)]
    merged_map = OrderedDict()
    for doc in prioritized_docs[:METADATA_PREFILTER_K] + base_docs:
        key = (doc.metadata.get("case_number"), doc.page_content)
        merged_map[key] = doc
    return list(merged_map.values())

def retrieve_candidates(question: str, mode_name: str = ACTIVE_MODE, verbose: bool = True):
    article_number = extract_query_article(question)
    search_queries = expand_queries(question)
    bm25_retriever = mode_resources[mode_name]["bm25_retriever"]
    scored_candidates = {}

    if article_number:
        logger.info("Soft metadata bias enabled | mode=%s | article=%s", mode_name, article_number)

    for q in search_queries:
        vector_docs = collect_vector_candidates(q, article_number, mode_name)
        bm25_docs = bm25_retriever.invoke(q)
        results = vector_docs + bm25_docs
        if verbose:
            print(f"\n[{mode_name}] Query: {q}")
            print(f"검색 결과: {len(results)}개")
        for rank, doc in enumerate(results):
            key = (doc.metadata.get("case_number"), doc.page_content)
            base_score = 1 / (rank + 1)
            bonus = metadata_soft_score(doc, article_number) + document_type_bonus(doc, mode_name)
            previous = scored_candidates.get(key, {"score": 0.0})["score"]
            scored_candidates[key] = {
                "doc": doc,
                "score": max(previous, base_score + bonus),
            }

    ranked_candidates = sorted(scored_candidates.values(), key=lambda item: item["score"], reverse=True)
    unique_docs = [item["doc"] for item in ranked_candidates[:VECTOR_SEARCH_TOP_K]]

    if verbose:
        print(f"\n[{mode_name}] 후보 문서 수:", len(unique_docs))
        log_documents(f"retrieved documents [{mode_name}]", unique_docs, limit=RETRIEVAL_SAMPLE_SIZE)
        print(f"\n[{mode_name}] Retrieval 샘플 확인")
        for idx, doc in enumerate(unique_docs[:RETRIEVAL_SAMPLE_SIZE], 1):
            print(f"[{idx}] case_number={doc.metadata.get('case_number')} | type={doc.metadata.get('document_type')} | article={doc.metadata.get('article')}")
            print(doc.page_content[:300])
            print("-" * 80)

    return {"mode": mode_name, "article_filter": article_number, "queries": search_queries, "documents": unique_docs}

retrieval_result = retrieve_candidates(query, mode_name=ACTIVE_MODE)
queries = retrieval_result["queries"]
unique_docs = retrieval_result["documents"]

INFO | retrieved documents [case_plus_qa] | count=20
INFO | retrieved documents [case_plus_qa] #1 | case=93다3073,93다3080 | type=case_law | article=None | preview=본소에 관한 논지는 모두 이유 없다. 2. 반소에 관하여 저작권법에 의하여 보호되는 저작물은 학문과 예술에 관하여 사람의 정신적 노력에 의하여 얻어진 사상 또는 감정의 창작적 표현물이어야 하는 것이고 ( 당원 1979.12.28. 선고 79도1482 판결 ; 1990.10.23. 선고
INFO | retrieved documents [case_plus_qa] #2 | case=2009도6073 | type=case_law | article=['4'] | preview=【주 문】  원심판결을 파기하고, 사건을 서울중앙지방법원에 환송한다.  이 유  상고이유를 판단한다.  구 저작권법(2006. 12. 28. 법률 제8101호로 전문 개정되기 전의 것, 이하 같다) 제4조 제1항 제8호  는 "지도, 도표, 설계도, 약도, 모형 그 밖의 도형저작물"을
INFO | retrieved documents [case_plus_qa] #3 | case=2007다63409 | type=case_law | article=['5'] | preview=소정의 2차적저작물로 보호받기 위하여는 원저작물을 기초로 하되 원저작물과 실질적 유사성을 유지하고 이것에 사회통념상 새로운 저작물이 될 수 있을 정도의 수정·증감을 가하여 새로운 창작성을 부가하여야 하는 것이므로 ( 대법원 2002. 1. 25. 선고 99도863 판결 , 대법원 200
INFO | retrieved documents [case_plus_qa] #4 | case=2011도3599 | type=case_law | article=['5'] | preview=【주 문】상고를 모두 기각한다. 이    유 상고이유를 판단한다. 1. 저작권법 제5조 제1항 은 ‘원저작물을 번역·편곡·변형·각색·영상제작 그 밖의 방법으로 작성한 창작물’을 ‘2차적저작물’이라고 규정하고 있는바, 2차적저작물이 되기 위해서는 원저작물을 기초로 수정·증감이 가해지되 원
INFO | retrieved documents [case_plus_qa] #5 | case=QA-19 | type=qa | article=['16', '28', '26', '29', '32', '34', '35'] | preview=질문: 리포트나 논문의 작성 시 다른 어문저작물을 인용한 경우에도 저작권 침해의 문제가 발생할 수 있을까요?

[case_plus_qa] Query: 저작권 보호 대상이 되는 저작물의 요건은 무엇인가?
검색 결과: 40개

[case_plus_qa] Query: 저작권 보호 대상 저작물의 요건은 무엇인가?
검색 결과: 40개

[case_plus_qa] 후보 문서 수: 20

[case_plus_qa] Retrieval 샘플 확인
[1] case_number=93다3073,93다3080 | type=case_law | article=None
본소에 관한 논지는 모두 이유 없다.
2. 반소에 관하여
저작권법에 의하여 보호되는 저작물은 학문과 예술에 관하여 사람의 정신적 노력에 의하여 얻어진 사상 또는 감정의 창작적 표현물이어야 하는 것이고
(
당원 1979.12.28. 선고 79도1482 판결
;
1990.10.23. 선고 90다카8845 판결
),
따라서 저작권법이 보호하고 있는 것은 사상, 감정을 말, 문자, 음, 색 등에 의하여 구체적으로 외부에 표현된 창작적인 표현형식이고, 그 표현되어 있는 내용 즉 아이디어나 이론 등의 사상 및 감정 그 자체는 설사 그것이 독창
--------------------------------------------------------------------------------
[2] case_number=2009도6073 | type=case_law | article=['4']
【주 문】
 원심판결을 파기하고, 사건을 서울중앙지방법원에 환송한다.
 이 유
 상고이유를 판단한다.
 구 저작권법(2006. 12. 28. 법률 제8101호로 전문 개정되기 전의 것, 이하 같다) 제4조 제1항 제8호
 는 "지도, 도표, 설계도, 약도, 모형 그 밖의 도형저작물"을 저작물의 하나로 예시하고 있는데, 이와 같은 도형저작물은 예술성의 표현보다는 기능이나 실용적인 사상의 표현을 주된 목적으로 하는 이른바 기능적 저작물로서, 기능적 저작물은 그 표현하고자 하는 기능 또는 실용적인 사상이 속하는 분야에서의 일반적인 표현방
--------------------------------------------------------------------------------
[3] case_number=2007다63409 | type=case_law | article=['5']
소정의 2차적저작물로 보호받기 위하여는 원저작물을 기초로 하되 원저작물과 실질적 유사성을 유지하고 이것에 사회통념상 새로운 저작물이 될 수 있을 정도의 수정·증감을 가하여 새로운 창작성을 부가하여야 하는 것이므로
(
대법원 2002. 1. 25. 선고 99도863 판결
,
대법원 2004. 7. 8. 선고 2004다18736 판결
등 참조),
어떤 저작물이 기존의 저작물을 다소 이용하였더라도 기존의 저작물과 실질적인 유사성이 없는 별개의 독립적인 신 저작물이 되었다면, 이는 창작으로서 기존의 저작물의 저작권을 침해한 것이 되지 아니
--------------------------------------------------------------------------------
[4] case_number=2011도3599 | type=case_law | article=['5']
【주 문】상고를 모두 기각한다.
이    유
상고이유를 판단한다.
1.
저작권법 제5조 제1항
은 ‘원저작물을 번역·편곡·변형·각색·영상제작 그 밖의 방법으로 작성한 창작물’을 ‘2차적저작물’이라고 규정하고 있는바, 2차적저작물이 되기 위해서는 원저작물을 기초로 수정·증감이 가해지되 원저작물과 실질적 유사성을 유지하여야 한다. 따라서 어문저작물인 원저작물을 기초로 하여 이를 요약한 요약물이 원저작물과 실질적인 유사성이 없는 별개의 독립적인 새로운 저작물이 된 경우에는 원저작물 저작권자의 2차적저작물작성권을 침해한 것으로 되지는 아니
--------------------------------------------------------------------------------
[5] case_number=QA-19 | type=qa | article=['16', '28', '26', '29', '32', '34', '35']
질문: 리포트나 논문의 작성 시 다른 어문저작물을 인용한 경우에도 저작권 침해의 문제가 발생할 수 있을까요?
--------------------------------------------------------------------------------

### Reranking

In [20]:
from sentence_transformers import CrossEncoder

reranker = CrossEncoder("BAAI/bge-reranker-large")

def cosine_similarity(vec_a, vec_b):
    return float(np.dot(vec_a, vec_b) / (np.linalg.norm(vec_a) * np.linalg.norm(vec_b)))

def deduplicate_context(documents, similarity_threshold=DEDUP_SIMILARITY_THRESHOLD):
    if not documents or not ENABLE_CONTEXT_DEDUP:
        return documents
    embeddings = np.array(embedding_model.embed_documents([doc.page_content for doc in documents]))
    unique_docs = []
    unique_vectors = []
    for doc, vector in zip(documents, embeddings):
        if not unique_vectors:
            unique_docs.append(doc)
            unique_vectors.append(vector)
            continue
        similarities = [cosine_similarity(vector, existing_vector) for existing_vector in unique_vectors]
        if max(similarities) < similarity_threshold:
            unique_docs.append(doc)
            unique_vectors.append(vector)
    return unique_docs

def compose_final_documents(reranked_docs, mode_name: str, top_k: int = RERANK_TOP_K):
    if mode_name != "case_plus_qa":
        return reranked_docs[:top_k]

    qa_docs = [doc for doc in reranked_docs if doc.metadata.get("document_type") == "qa"]
    case_docs = [doc for doc in reranked_docs if doc.metadata.get("document_type") == "case_law"]
    selected = []
    selected.extend(case_docs[:FINAL_CASE_DOCS])
    selected.extend(qa_docs[:FINAL_QA_DOCS])
    if len(selected) < top_k:
        seen = {(d.metadata.get("case_number"), d.page_content) for d in selected}
        for doc in reranked_docs:
            key = (doc.metadata.get("case_number"), doc.page_content)
            if key not in seen:
                selected.append(doc)
                seen.add(key)
            if len(selected) == top_k:
                break
    return selected[:top_k]

def rerank_documents(question: str, candidate_docs, mode_name: str = ACTIVE_MODE, top_k: int = RERANK_TOP_K):
    if not candidate_docs:
        return []
    pairs = [(question, doc.page_content) for doc in candidate_docs]
    scores = reranker.predict(pairs)
    scored_docs = []
    for score, doc in zip(scores, candidate_docs):
        adjusted_score = float(score) + document_type_bonus(doc, mode_name)
        scored_docs.append((adjusted_score, doc))
    scored_docs.sort(key=lambda item: item[0], reverse=True)
    reranked_docs = [doc for _, doc in scored_docs]
    post_processed_docs = deduplicate_context(reranked_docs)
    selected_docs = compose_final_documents(post_processed_docs, mode_name=mode_name, top_k=top_k)
    log_documents(f"reranked results [{mode_name}]", selected_docs, limit=RETRIEVAL_SAMPLE_SIZE)
    return selected_docs

selected_docs = rerank_documents(query, unique_docs, mode_name=ACTIVE_MODE)

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 11215.78it/s]
XLMRobertaForSequenceClassification LOAD REPORT from: BAAI/bge-reranker-large
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
INFO | Use pytorch device: mps
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.42s/it]
INFO | reranked results [case_plus_qa] | count=5
INFO | reranked results [case_plus_qa] #1 | case=2011도3599 | type=case_law | article=['5'] | preview=【주 문】상고를 모두 기각한다. 이    유 상고이유를 판단한다. 1. 저작권법 제5조 제1항 은 ‘원저작물을 번역·편곡·변형·각색·영상제작 그 밖의 방법으로 작성한 창작물’을 ‘2차적저작물’이라고 규정하고 있는바, 2차적저작물이 되기 위해서는 원저작물을 기초로 수정·증감이 가해지되 원
INFO | reranked results [case_plus_qa] #2 | case=2009도6073 | type=case_law | article=['4'] | preview=【주 문】  원심판결을 파기하고, 사건을 서울중앙지방법원에 환송한다.  이 유  상고이유를 판단한다.  구 저작권법(2006. 12. 28. 법률 제8101호로 전문 개정되기 전의 것, 이하 같다) 제4조 제1항 제8호  는 "지도, 도표, 설계도, 약도, 모형 그 밖의 도형저작물"을
INFO | reranked results [case_plus_qa] #3 | case=94도2238 | type=case_law | article=['2', '23'] | preview= 상고이유를 본다. 1. 저작권법에 의하여 보호되는 저작물이기 위하여는 문학·학술 또는 예술의 범위에 속하는 창작물이어야 하므로(저작권법 제2조 제1호) 그 요건으로서 창작성이 요구되나 여기서 말하는 창작성이란 완전한 의미의 독창성을 말하는 것은 아니며 단지 어떠한 작품이 남의 것을 단
INFO | reranked results [case_plus_qa] #4 | case=QA-17 | type=qa | article=['2', '7'] | preview= 답변: 신문기자의 창작성이 반영된 일반적인 신문기사를 그대로 이용하였다면 저작권 침해에 해당할 수 있습니다.저작권법에서 보호하는 저작물은 ‘인간의 사상 또는 감정을 표현한 창작물’ 을 의미합니다(저작권법 제2조 제1호). ​대부분의 기사의 경우 기자의 사상과 감정이 표현되어, 창작성이
INFO | reranked results [case_plus_qa] #5 | case=QA-13 | type=qa | article=[] | preview= 답변: 추상적인 게임의 장르, 기본적인 배경, 전개방식, 규칙, 단계변화 등은 게임의 개념ㆍ방식ㆍ해법ㆍ창작도구로서 아이디어에 해당하여 저작권법에 의한 보호를 받을 수 없다. 그러나 최근 법원은 ‘개발자의 제작 의도와 시나리오에 따라 기술적으로 구현된 주요한 구성요소들이 선택ㆍ배열되고

In [21]:
# 상위 context 선택
top_k = RERANK_TOP_K
print(f"\n[{ACTIVE_MODE}] Top {top_k} Context 선택", len(selected_docs))
for i, doc in enumerate(selected_docs, 1):
    print(f"\n[Document {i}]")
    print("metadata:", doc.metadata)
    print("content preview:", doc.page_content[:300])
    print("-" * 80)

[case_plus_qa] Top 5 Context 선택 5

[Document 1]
metadata: {'court': '대법원', 'date': '2013.08.22', 'article': ['5'], 'article_count': 1, 'case_number': '2011도3599', 'document_type': 'case_law', 'ho': ['1']}
content preview: 【주 문】상고를 모두 기각한다.
이    유
상고이유를 판단한다.
1.
저작권법 제5조 제1항
은 ‘원저작물을 번역·편곡·변형·각색·영상제작 그 밖의 방법으로 작성한 창작물’을 ‘2차적저작물’이라고 규정하고 있는바, 2차적저작물이 되기 위해서는 원저작물을 기초로 수정·증감이 가해지되 원저작물과 실질적 유사성을 유지하여야 한다. 따라서 어문저작물인 원저작물을 기초로 하여 이를 요약한 요약물이 원저작물과 실질적인 유사성이 없는 별개의 독립적인 새로운 저작물이 된 경우에는 원저작물 저작권자의 2차적저작물작성권을 침해한 것으로 되지는 아니
--------------------------------------------------------------------------------

[Document 2]
metadata: {'court': '대법원', 'ho': ['1'], 'case_number': '2009도6073', 'article': ['4'], 'document_type': 'case_law', 'date': '2011.05.13', 'article_count': 1}
content preview: 【주 문】
 원심판결을 파기하고, 사건을 서울중앙지방법원에 환송한다.
 이 유
 상고이유를 판단한다.
 구 저작권법(2006. 12. 28. 법률 제8101호로 전문 개정되기 전의 것, 이하 같다) 제4조 제1항 제8호
 는 "지도, 도표, 설계도, 약도, 모형 그 밖의 도형저작물"을 저작물의 하나로 예시하고 있는데, 이와 같은 도형저작물은 예술성의 표현보다는 기능이나 실용적인 사상의 표현을 주된 목적으로 하는 이른바 기능적 저작물로서, 기능적 저작물은 그 표현하고자 하는 기능 또는 실용적인 사상이 속하는 분야에서의 일반적인 표현방
--------------------------------------------------------------------------------

[Document 3]
metadata: {'date': '1995.11.14', 'article': ['2', '23'], 'court': '대법원', 'case_number': '94도2238', 'document_type': 'case_law', 'article_count': 2, 'ho': ['1', '2']}
content preview:
상고이유를 본다. 1. 저작권법에 의하여 보호되는 저작물이기 위하여는 문학·학술 또는 예술의 범위에 속하는 창작물이어야 하므로(저작권법 제2조 제1호) 그 요건으로서 창작성이 요구되나 여기서 말하는 창작성이란 완전한 의미의 독창성을 말하는 것은 아니며 단지 어떠한 작품이 남의 것을 단순히 모방한 것이 아니고 작자 자신의 독자적인 사상 또는 감정의 표현을 담고 있음을 의미할 뿐이어서 이러한 요건을 충족하기 위하여는 단지 저작물에 그 저작자 나름대로의 정신적 노력의 소산으로서의 특성이 부여되어 있고 다른 저작자의 기존의 작품과 구별할
--------------------------------------------------------------------------------

[Document 4]
metadata: {'article_count': 2, 'case_number': 'QA-17', 'document_type': 'qa', 'court': 'QnA', 'ho': ['1'], 'date': 'N/A', 'article': ['2', '7']}
content preview:
답변: 신문기자의 창작성이 반영된 일반적인 신문기사를 그대로 이용하였다면 저작권 침해에 해당할 수 있습니다.저작권법에서 보호하는 저작물은 ‘인간의 사상 또는 감정을 표현한 창작물’ 을 의미합니다(저작권법 제2조 제1호). ​대부분의 기사의 경우 기자의 사상과 감정이 표현되어, 창작성이 드러나므로 저작권법의 보호를 받을 수 있습니다. 따라서 이러한 기사를 블로그나 게시판 등에 게재한 경우라면 저작권 침해에 해당할 수 있을 것입니다.​그러나 저작권법 제7조 ‘보호받지 못하는 저작물’ 중 제5호는 “사실의 전달에 불과한 시사보도” 를
--------------------------------------------------------------------------------

[Document 5]
metadata: {'document_type': 'qa', 'case_number': 'QA-13', 'court': 'QnA', 'date': 'N/A', 'article': [], 'ho': [], 'article_count': 0}
content preview:
답변: 추상적인 게임의 장르, 기본적인 배경, 전개방식, 규칙, 단계변화 등은 게임의 개념ㆍ방식ㆍ해법ㆍ창작도구로서 아이디어에 해당하여 저작권법에 의한 보호를 받을 수 없다. 그러나 최근 법원은 ‘개발자의 제작 의도와 시나리오에 따라 기술적으로 구현된 주요한 구성요소들이 선택ㆍ배열되고 유기적인 조합을 이루어 선행 게임물과 확연히 구별되는 창작적 개성이 있는 부분’대해 저작물성을 인정하고 있으므로 저작권 침해 가능성에 유의해야 할 것이다.우선 저작권법의 보호 대상은 인간의 사상 또는 감정을 말, 문자, 음, 색 등에 의하여 구체적으로
--------------------------------------------------------------------------------

## Runtime: Step3. LLM request (RAG Chain 구성)

In [22]:
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

answer_llm = ChatOpenAI(model="gpt-5.2", temperature=0.05)

prompt = ChatPromptTemplate.from_template("""
당신은 저작권법 전문가입니다.

규칙:
1. 반드시 제공된 참고 문맥의 내용만 사용하세요.
2. 답변에는 관련 조문 번호(예: 제2조, 제35조의3)와 Source를 반드시 포함하세요.
3. 참고 문맥에 없는 정보는 추측하지 마세요.
4. 답을 찾을 수 없으면 반드시 정확히 "정보를 찾을 수 없습니다"라고 답하세요.
5. 질문이 QA형이면 불필요하게 장황하게 쓰지 말고, 문맥에 근거한 핵심 답을 먼저 간결하게 제시하세요.
6. QA 문서와 판례 문서가 함께 있으면, QA 문서의 직접 답변을 우선 활용하되 판례 Source도 함께 제시하세요.

[참고 문맥]
{context}

[질문]
{question}

[답변 형식]
- 핵심 답변
- 근거 조문/판례
- Source
""")

def format_docs(documents):
    formatted = []
    for idx, doc in enumerate(documents, 1):
        source = doc.metadata.get("case_number", "N/A")
        articles = doc.metadata.get("article") or []
        ho_list = doc.metadata.get("ho") or []
        article_text = ", ".join(f"제{article}조" for article in articles[:5]) or "조문 정보 없음"
        ho_text = ", ".join(f"제{ho}항" for ho in ho_list[:5]) or "항 정보 없음"
        formatted.append(f"[Source {idx}] case_number={source} | document_type={doc.metadata.get('document_type')} | article={article_text} | ho={ho_text}\n{doc.page_content}")
    return "\n\n".join(formatted)

rag_chain = prompt | answer_llm | StrOutputParser()

def generate_answer(question: str, selected_docs, mode_name: str = ACTIVE_MODE):
    context = format_docs(selected_docs)
    logger.info("final context | mode=%s | chars=%s", mode_name, len(context))
    logger.info("final context preview | %s", context[:1500].replace("\n", " "))
    answer = rag_chain.invoke({"context": context, "question": question})
    return answer, context

print("RAG Chain 구성 완료")
answer, context = generate_answer(query, selected_docs, mode_name=ACTIVE_MODE)
print("\n최종 Context 길이:", len(context))

INFO | final context | mode=case_plus_qa | chars=9918
INFO | final context preview | [Source 1] case_number=2011도3599 | document_type=case_law | article=제5조 | ho=제1항 【주 문】상고를 모두 기각한다. 이    유 상고이유를 판단한다. 1. 저작권법 제5조 제1항 은 ‘원저작물을 번역·편곡·변형·각색·영상제작 그 밖의 방법으로 작성한 창작물’을 ‘2차적저작물’이라고 규정하고 있는바, 2차적저작물이 되기 위해서는 원저작물을 기초로 수정·증감이 가해지되 원저작물과 실질적 유사성을 유지하여야 한다. 따라서 어문저작물인 원저작물을 기초로 하여 이를 요약한 요약물이 원저작물과 실질적인 유사성이 없는 별개의 독립적인 새로운 저작물이 된 경우에는 원저작물 저작권자의 2차적저작물작성권을 침해한 것으로 되지는 아니하는데 ( 대법원 2010. 2. 11. 선고 2007다63409 판결 등 참조), 여기서 요약물이 그 원저작물과 사이에 실질적인 유사성이 있는지 여부는, 요약물이 원저작물의 기본으로 되는 개요, 구조, 주된 구성 등을 그대로 유지하고 있는지 여부, 요약물이 원저작물을 이루는 문장들 중 일부만을 선택하여 발췌한 것이거나 발췌한 문장들의 표현을 단순히 단축한 정도에 불과한지 여부, 원저작물과 비교한 요약물의 상대적인 분량, 요약물의 원저작물에 대한 대체가능성 여부 등을 종합적으로 고려하여 판단해야 한다. 한편 저작권의 보호 대상은 인간의 사상 또는 감정을 말, 문자, 음, 색 등에 의하여 구체적으로 외부에 표현한 창작적인 표현형식이고, 거기에 표현되어 있는 내용 즉 아이디어나 이론 등의 사상 또는 감정 그 자체는 원칙적으로 저작권의 보호 대상이 아니므로, 저작권의 침해 여부를 가리기 위하여 두 저작물 사이에 실질적인 유사성이 있는지 여부를 판단함에 있어서도 창작적인 표현형식에 해당하는 것만을 가지고 대비해 보아야 하고, 표현형식이 아닌 사상 또는 감정 그 자체에 독창성·신규성이 있는지를 고려하여서는 안 된다( 대법원 2011. 2. 10. 선고 2009도291 판결 등 참조).  [Source 2] case_number=2009도6073 | document_type=case_law | article=제4조 | ho=제1항 【주 문】  원심판결을 파기하고, 사건을 서울중앙지방법원에 환송한다.  이 유  상고이유를 판단한다.  구 저작권법(2006. 12. 28. 법률 제8101호로 전문 개정되기 전의 것, 이하 같다) 제4조 제1항 제8호  는 "지도, 도표, 설계도, 약도, 모형 그 밖의 도형저작물"을 저작물의 하나로 예시하고 있는데, 이와 같은 도형저작물은 예술성의 표현보다는 기능이나 실용적인 사상의 표현을 주된 목적으로 하는 이른바 기능적 저작물로서, 기능적 저작물은 그 표현하고자 하는 기능 또는 실용적인 사상이 속하는 분야에서의 일반적인 표현방법, 규격 또는 그 용도나 기능 자체, 저작물 이용자의 이해의 편의성 등에 의하여 그 표현이 제한되는 경우가 많으므로 작성자의 창조적 개성이 드러나지 않을 가능성이 크지만, 기능적 저작물도 구 저작권법의 보호대상이 되기 위해서

RAG Chain 구성 완료

최종 Context 길이: 9918

In [23]:
# 최종 프롬프트 확인
final_prompt = prompt.invoke({"context": format_docs(selected_docs), "question": query})
print(final_prompt.messages[0].content)
print(answer)

당신은 저작권법 전문가입니다.

규칙:
1. 반드시 제공된 참고 문맥의 내용만 사용하세요.
2. 답변에는 관련 조문 번호(예: 제2조, 제35조의3)와 Source를 반드시 포함하세요.
3. 참고 문맥에 없는 정보는 추측하지 마세요.
4. 답을 찾을 수 없으면 반드시 정확히 "정보를 찾을 수 없습니다"라고 답하세요.
5. 질문이 QA형이면 불필요하게 장황하게 쓰지 말고, 문맥에 근거한 핵심 답을 먼저 간결하게 제시하세요.
6. QA 문서와 판례 문서가 함께 있으면, QA 문서의 직접 답변을 우선 활용하되 판례 Source도 함께 제시하세요.

[참고 문맥]
[Source 1] case_number=2011도3599 | document_type=case_law | article=제5조 | ho=제1항
【주 문】상고를 모두 기각한다.
이    유
상고이유를 판단한다.
1.
저작권법 제5조 제1항
은 ‘원저작물을 번역·편곡·변형·각색·영상제작 그 밖의 방법으로 작성한 창작물’을 ‘2차적저작물’이라고 규정하고 있는바, 2차적저작물이 되기 위해서는 원저작물을 기초로 수정·증감이 가해지되 원저작물과 실질적 유사성을 유지하여야 한다. 따라서 어문저작물인 원저작물을 기초로 하여 이를 요약한 요약물이 원저작물과 실질적인 유사성이 없는 별개의 독립적인 새로운 저작물이 된 경우에는 원저작물 저작권자의 2차적저작물작성권을 침해한 것으로 되지는 아니하는데
(
대법원 2010. 2. 11. 선고 2007다63409 판결
등 참조),
여기서 요약물이 그 원저작물과 사이에 실질적인 유사성이 있는지 여부는, 요약물이 원저작물의 기본으로 되는 개요, 구조, 주된 구성 등을 그대로 유지하고 있는지 여부, 요약물이 원저작물을 이루는 문장들 중 일부만을 선택하여 발췌한 것이거나 발췌한 문장들의 표현을 단순히 단축한 정도에 불과한지 여부, 원저작물과 비교한 요약물의 상대적인 분량, 요약물의 원저작물에 대한 대체가능성 여부 등을 종합적으로 고려하여 판단해야 한다.
한편 저작권의 보호 대상은 인간의 사상 또는 감정을 말, 문자, 음, 색 등에 의하여 구체적으로 외부에 표현한 창작적인 표현형식이고, 거기에 표현되어 있는 내용 즉 아이디어나 이론 등의 사상 또는 감정 그 자체는 원칙적으로 저작권의 보호 대상이 아니므로, 저작권의 침해 여부를 가리기 위하여 두 저작물 사이에 실질적인 유사성이 있는지 여부를 판단함에 있어서도 창작적인 표현형식에 해당하는 것만을 가지고 대비해 보아야 하고, 표현형식이 아닌 사상 또는 감정 그 자체에 독창성·신규성이 있는지를 고려하여서는 안 된다(
대법원 2011. 2. 10. 선고 2009도291 판결
등 참조).

[Source 2] case_number=2009도6073 | document_type=case_law | article=제4조 | ho=제1항
【주 문】
 원심판결을 파기하고, 사건을 서울중앙지방법원에 환송한다.
 이 유
 상고이유를 판단한다.
 구 저작권법(2006. 12. 28. 법률 제8101호로 전문 개정되기 전의 것, 이하 같다) 제4조 제1항 제8호
 는 "지도, 도표, 설계도, 약도, 모형 그 밖의 도형저작물"을 저작물의 하나로 예시하고 있는데, 이와 같은 도형저작물은 예술성의 표현보다는 기능이나 실용적인 사상의 표현을 주된 목적으로 하는 이른바 기능적 저작물로서, 기능적 저작물은 그 표현하고자 하는 기능 또는 실용적인 사상이 속하는 분야에서의 일반적인 표현방법, 규격 또는 그 용도나 기능 자체, 저작물 이용자의 이해의 편의성 등에 의하여 그 표현이 제한되는 경우가 많으므로 작성자의 창조적 개성이 드러나지 않을 가능성이 크지만, 기능적 저작물도 구 저작권법의 보호대상이 되기 위해서는 작성자의 창조적 개성이 나타나 있어야 할 것임은 물론이다(
 대법원 2005. 1. 27. 선고 2002도965 판결
 등 참조). 그리고 기능적 저작물에 있어서 구 저작권법은 그 기능적 저작물이 담고 있는 기술사상을 보호하는 것이 아니라 그 기능적 저작물의 창작성 있는 표현을 보호하는 것이므로, 설령 종전의 저작물 등과 다소간의 차이가 있다고 하더라도 그러한 사정만으로 그러한 기능적 저작물의 창작성을 인정할 수는 없고 작성자의 창조적 개성이 드러나 있는지 여부를 별도로 판단하여야 할 것이다(
 대법원 2007. 8. 24. 선고 2007도4848 판결
 참조).

[Source 3] case_number=94도2238 | document_type=case_law | article=제2조, 제23조 | ho=제1항, 제2항

상고이유를 본다. 1. 저작권법에 의하여 보호되는 저작물이기 위하여는 문학·학술 또는 예술의 범위에 속하는 창작물이어야 하므로(저작권법 제2조 제1호) 그 요건으로서 창작성이 요구되나 여기서 말하는 창작성이란 완전한 의미의 독창성을 말하는 것은 아니며 단지 어떠한 작품이 남의 것을 단순히 모방한 것이 아니고 작자 자신의 독자적인 사상 또는 감정의 표현을 담고 있음을 의미할 뿐이어서 이러한 요건을 충족하기 위하여는 단지 저작물에 그 저작자 나름대로의 정신적 노력의 소산으로서의 특성이 부여되어 있고 다른 저작자의 기존의 작품과 구별할 수 있을 정도이면 충분하다고 할 것이다. 기록에 의하여 피해자 공소외 1이 저술한 "○○○기술개론"을 기존의 한국세탁업협회에서 발행한 교재들 및 서울대 공소외 2, 공소외 3 교수의 공동저작인 "△△관리학" 등과 비교하여 보면, 부분적으로는 동일, 유사한 표현이 존재하는 것은 사실이나 전체적인 구성이나 표현형식에 있어서는 위에 나온 기존의 다른 책자들과 뚜렷이 구별할 수 있다 할 것이어서 그 창작성을 인정할 수 있으므로 위 "○○○기술개론"이 저작권법 소정의 저작물에 해당하지 아니한다고 할 수 없다(가사 공소외 1의 저작이 원저작물과의 관계에서 이것을 토대로 하였다는 의미에서의 종속성을 인정할 수 있어 소위 2차적 저작물에 해당한다 할지라도 원저작자에 대한 관계에서 저작권 침해로 되는 것은 별문제로 하고 저작권법상 2차적 저작물로서 보호되는 것이라 할 것이다). 원심이 같은 취지에서 피고인의 그 판시소위를 저작물에 관한 권리를 침해한 경우에 해당한다고 보아 저작권법 위반죄로 처단한 조치는 정당하고 거기에 소론이 지적하는 바와 같은 저작권에 관한 법리를 오해한 위법 등이 있다고 할 수 없다. 논지는 이유 없다. 2. 또, 기록에 의하여 관계 증거를 살펴보면, 피고인이 저작한 "국민의생활에 따른 의복관리와 세탁기술"이라는 책자가 학교나 학원 등에서의 교육을 위하여 저작된 것으로서 저작권법 제23조 제1항에 규정된 교과용도서이거나 피고인이 같은 조 제2항에 규정된 교육기관임을 인정할 증거가 없다고 본 원심판단에도 수긍이 가고, 거기에 소론과 같이 채증법칙 위배나 이유불비 등의 위법이 있다고 할 수 없다. 논지도 이유 없다. 3. 그러므로 상고를 기각하기로 하여 관여 법관의 일치된 의견으로 주문과 같이 판결한다.대법관 이임수(재판장) 김석수 정귀호(주심) 이돈희

[Source 4] case_number=QA-17 | document_type=qa | article=제2조, 제7조 | ho=제1항

답변: 신문기자의 창작성이 반영된 일반적인 신문기사를 그대로 이용하였다면 저작권 침해에 해당할 수 있습니다.저작권법에서 보호하는 저작물은 ‘인간의 사상 또는 감정을 표현한 창작물’ 을 의미합니다(저작권법 제2조 제1호). ​대부분의 기사의 경우 기자의 사상과 감정이 표현되어, 창작성이 드러나므로 저작권법의 보호를 받을 수 있습니다. 따라서 이러한 기사를 블로그나 게시판 등에 게재한 경우라면 저작권 침해에 해당할 수 있을 것입니다.​그러나 저작권법 제7조 ‘보호받지 못하는 저작물’ 중 제5호는 “사실의 전달에 불과한 시사보도” 를 규정하고 있습니다. 이는 사실관계를 육하원칙에 따라 있는 그대로 보도한 것을 의미합니다. ​판례는 단순한 사실보도, 부고, 주식시세 등과 같이 작성자의 사상이나 표현이 가미되지 아니한 신문기사는 보호받지 못하는 저작물로 분류하고, 기자의 창작성이 반영된 일반적인 신문기사는 저작물에 해당하여 저작권법의 보호를 받는다고 판시하였습니다.​​● 대법원 2009. 5. 28. 선고 2007다354 판결.뉴스통신사 사이에서 기사를 무단으로 전재하여 손해배상청구소송이 제기된 사안에서, 법원은 “독창적이고 개성 있는 표현 수준에 이르지 않고 ‘사실의 전달에 불과한 시사보도’ 의 정도에 그친것은 저작권법에 의한 보호 대상에서 제외한 것이라고 할 것이지만, 일부 문장의 배열 순서 및 그 구체적인 표현 등에 있어 다소의 수정․증감이나 변형이 가하여진 것이라 하더라도, 그에 대응하는 원고의 기사 중 핵심적인 표현부분을 그대로 전재하고 있을 뿐만 아니라, 전체적인 기사의 구성과 논조 등에 있어서 원고 기사의 창작적 특성이 감지되므로, 양 기사 사이에 실질적인 유사성이 있다.” 고 판시하면서 저작권 침해를 인정하였다.이 법에서 사용하는 용어의 뜻은 다음과 같다. <개정 2009. 4. 22., 2011. 6. 30., 2011. 12. 2., 2016. 3. 22.>1. "저작물"은 인간의 사상 또는 감정을 표현한 창작물을 말한다.2. "저작자"는 저작물을 창작한 자를 말한다.3. "공연"은 저작물 또는 실연ㆍ음반ㆍ방송을 상연ㆍ연주ㆍ가창ㆍ구연ㆍ낭독ㆍ상영ㆍ재생 그 밖의 방법으로 공중에게 공개하는 것을 말하며, 동일인의 점유에 속하는 연결된 장소 안에서 이루어지는 송신(전송을 제외한다)을 포함한다.4. "실연자"는 저작물을 연기ㆍ무용ㆍ연주ㆍ가창ㆍ구연ㆍ낭독 그 밖의 예능적 방법으로 표현하거나 저작물이 아닌 것을 이와 유사한 방법으로 표현하는 실연을 하는 자를 말하며, 실연을 지휘, 연출 또는 감독하는 자를 포함한다.5. "음반"은 음(음성ㆍ음향을 말한다. 이하 같다)이 유형물에 고정된 것(음을 디지털화한 것을 포함한다)을 말한다. 다만, 음이 영상과 함께 고정된 것을 제외한다.6. "음반제작자"는 음반을 최초로 제작하는 데 있어 전체적으로 기획하고 책임을 지는 자를 말한다.7. "공중송신"은 저작물, 실연ㆍ음반ㆍ방송 또는 데이터베이스(이하 "저작물등"이라 한다)를 공중이 수신하거나 접근하게 할 목적으로 무선 또는 유선통신의 방법에 의하여 송신하거나 이용에 제공하는 것을 말한다.8. "방송"은 공중송신 중 공중이 동시에 수신하게 할 목적으로 음ㆍ영상 또는 음과 영상 등을 송신하는 것을 말한다.8의2. "암호화된 방송 신호"란 방송사업자나 방송사업자의 동의를 받은 자가 정당한 권한 없이 방송(유선 및 위성 통신의 방법에 의한 방송에 한한다)을 수신하는 것을 방지하거나 억제하기 위하여 전자적으로 암호화한 방송 신호를 말한다.9. "방송사업자"는 방송을 업으로 하는 자를 말한다.10. "전송(傳送)"은 공중송신 중 공중의 구성원이 개별적으로 선택한 시간과 장소에서 접근할 수 있도록 저작물등을 이용에 제공하는 것을 말하며, 그에 따라 이루어지는 송신을 포함한다.11. "디지털음성송신"은 공중송신 중 공중으로 하여금 동시에 수신하게 할 목적으로 공중의 구성원의 요청에 의하여 개시되는 디지털 방식의 음의 송신을 말하며, 전송을 제외한다.12. "디지털음성송신사업자"는 디지털음성송신을 업으로 하는 자를 말한다.13. "영상저작물"은 연속적인 영상(음의 수반여부는 가리지 아니한다)이 수록된 창작물로서 그 영상을 기계 또는 전자장치에 의하여 재생하여 볼 수 있거나 보고 들을 수 있는 것을 말한다.14. "영상제작자"는 영상저작물의 제작에 있어 그 전체를 기획하고 책임을 지는 자를 말한다.15. "응용미술저작물"은 물품에 동일한 형상으로 복제될 수 있는 미술저작물로서 그 이용된 물품과 구분되어 독자성을 인정할 수 있는 것을 말하며, 디자인 등을 포함한다.16. "컴퓨터프로그램저작물"은 특정한 결과를 얻기 위하여 컴퓨터 등 정보처리능력을 가진 장치(이하 "컴퓨터"라 한다) 내에서 직접 또는 간접으로 사용되는 일련의 지시ㆍ명령으로 표현된 창작물을 말한다.17. "편집물"은 저작물이나 부호ㆍ문자ㆍ음ㆍ영상 그 밖의 형태의 자료(이하 "소재"라 한다)의 집합물을 말하며, 데이터베이스를 포함한다.18. "편집저작물"은 편집물로서 그 소재의 선택ㆍ배열 또는 구성에 창작성이 있는 것을 말한다.19. "데이터베이스"는 소재를 체계적으로 배열 또는 구성한 편집물로서 개별적으로 그 소재에 접근하거나 그 소재를 검색할 수 있도록 한 것을 말한다.20. "데이터베이스제작자"는 데이터베이스의 제작 또는 그 소재의 갱신ㆍ검증 또는 보충(이하 "갱신등"이라 한다)에 인적 또는 물적으로 상당한 투자를 한 자를 말한다.21. "공동저작물"은 2인 이상이 공동으로 창작한 저작물로서 각자의 이바지한 부분을 분리하여 이용할 수 없는 것을 말한다.22. "복제"는 인쇄ㆍ사진촬영ㆍ복사ㆍ녹음ㆍ녹화 그 밖의 방법으로 일시적 또는 영구적으로 유형물에 고정하거나 다시 제작하는 것을 말하며, 건축물의 경우에는 그 건축을 위한 모형 또는 설계도서에 따라 이를 시공하는 것을 포함한다.23. "배포"는 저작물등의 원본 또는 그 복제물을 공중에게 대가를 받거나 받지 아니하고 양도 또는 대여하는 것을 말한다.24. "발행"은 저작물 또는 음반을 공중의 수요를 충족시키기 위하여 복제ㆍ배포하는 것을 말한다.25. "공표"는 저작물을 공연, 공중송신 또는 전시 그 밖의 방법으로 공중에게 공개하는 경우와 저작물을 발행하는 경우를 말한다.26. "저작권신탁관리업"은 저작재산권자, 배타적발행권자, 출판권자, 저작인접권자 또는 데이터베이스제작자의 권리를 가진 자를 위하여 그 권리를 신탁받아 이를 지속적으로 관리하는 업을 말하며, 저작물등의 이용과 관련하여 포괄적으로 대리하는 경우를 포함한다.27. "저작권대리중개업"은 저작재산권자, 배타적발행권자, 출판권자, 저작인접권자 또는 데이터베이스제작자의 권리를 가진 자를 위하여 그 권리의 이용에 관한 대리 또는 중개행위를 하는 업을 말한다.28. "기술적 보호조치"란 다음 각 목의 어느 하나에 해당하는 조치를 말한다.가. 저작권, 그 밖에 이 법에 따라 보호되는 권리의 행사와 관련하여 이 법에 따라 보호되는 저작물등에 대한 접근을 효과적으로 방지하거나 억제하기 위하여 그 권리자나 권리자의 동의를 받은 자가 적용하는 기술적 조치나. 저작권, 그 밖에 이 법에 따라 보호되는 권리에 대한 침해 행위를 효과적으로 방지하거나 억제하기 위하여 그 권리자나 권리자의 동의를 받은 자가 적용하는 기술적 조치29. "권리관리정보"는 다음 각 목의 어느 하나에 해당하는 정보나 그 정보를 나타내는 숫자 또는 부호로서 각 정보가 저작권, 그 밖에 이 법에 따라 보호되는 권리에 의하여 보호되는 저작물등의 원본이나 그 복제물에 부착되거나 그 공연ㆍ실행 또는 공중송신에 수반되는 것을 말한다.가. 저작물등을 식별하기 위한 정보나. 저작권, 그 밖에 이 법에 따라 보호되는 권리를 가진 자를 식별하기 위한 정보다. 저작물등의 이용 방법 및 조건에 관한 정보30. "온라인서비스제공자"란 다음 각 목의 어느 하나에 해당하는 자를 말한다.가. 이용자가 선택한 저작물등을 그 내용의 수정 없이 이용자가 지정한 지점 사이에서 정보통신망(「정보통신망 이용촉진 및 정보보호 등에 관한 법률」 제2조제1항제1호의 정보통신망을 말한다. 이하 같다)을 통하여 전달하기 위하여 송신하거나 경로를 지정하거나 연결을 제공하는 자나. 이용자들이 정보통신망에 접속하거나 정보통신망을 통하여 저작물등을 복제ㆍ전송할 수 있도록 서비스를 제공하거나 그를 위한 설비를 제공 또는 운영하는 자31. "업무상저작물"은 법인ㆍ단체 그 밖의 사용자(이하 "법인등"이라 한다)의 기획하에 법인등의 업무에 종사하는 자가 업무상 작성하는 저작물을 말한다.32. "공중"은 불특정 다수인(특정 다수인을 포함한다)을 말한다.33. "인증"은 저작물등의 이용허락 등을 위하여 정당한 권리자임을 증명하는 것을 말한다.34. "프로그램코드역분석"은 독립적으로 창작된 컴퓨터프로그램저작물과 다른 컴퓨터프로그램과의 호환에 필요한 정보를 얻기 위하여 컴퓨터프로그램저작물코드를 복제 또는 변환하는 것을 말한다.35. "라벨"이란 그 복제물이 정당한 권한에 따라 제작된 것임을 나타내기 위하여 저작물등의 유형적 복제물ㆍ포장 또는 문서에 부착ㆍ동봉 또는 첨부되거나 그러한 목적으로 고안된 표지를 말한다.36. "영화상영관등"이란 영화상영관, 시사회장, 그 밖에 공중에게 영상저작물을 상영하는 장소로서 상영자에 의하여 입장이 통제되는 장소를 말한다.다음 각 호의 어느 하나에 해당하는 것은 이 법에 의한 보호를 받지 못한다.1. 헌법ㆍ법률ㆍ조약ㆍ명령ㆍ조례 및 규칙2. 국가 또는 지방자치단체의 고시ㆍ공고ㆍ훈령 그 밖에 이와 유사한 것3. 법원의 판결ㆍ결정ㆍ명령 및 심판이나 행정심판절차 그 밖에 이와 유사한 절차에 의한 의결ㆍ결정 등4. 국가 또는 지방자치단체가 작성한 것으로서 제1호 내지 제3호에 규정된 것의 편집물 또는 번역물5. 사실의 전달에 불과한 시사보도

[Source 5] case_number=QA-13 | document_type=qa | article=조문 정보 없음 | ho=항 정보 없음

답변: 추상적인 게임의 장르, 기본적인 배경, 전개방식, 규칙, 단계변화 등은 게임의 개념ㆍ방식ㆍ해법ㆍ창작도구로서 아이디어에 해당하여 저작권법에 의한 보호를 받을 수 없다. 그러나 최근 법원은 ‘개발자의 제작 의도와 시나리오에 따라 기술적으로 구현된 주요한 구성요소들이 선택ㆍ배열되고 유기적인 조합을 이루어 선행 게임물과 확연히 구별되는 창작적 개성이 있는 부분’대해 저작물성을 인정하고 있으므로 저작권 침해 가능성에 유의해야 할 것이다.우선 저작권법의 보호 대상은 인간의 사상 또는 감정을 말, 문자, 음, 색 등에 의하여 구체적으로 외부에 표현한 창작적인 표현형식이다. 따라서 저작권 침해 여부를 가리기 위해서는 창작적인 표현형식에 해당하는 것만을 대상으로 한다. 여기서 창작성은 완전한 의미의 독창성을 요구하는 것은 아니나 저작자만의 독자적인 표현을 담고 있어야 한다. 즉 저작권 침해가 성립하기 위해서는 1) 아이디어가 아닌 창작적인 표현만을 비교 대상으로 하여, 2) 타인의 저작물에 의거하여 작성되고(의거성), 3) 원저작물과 창작적 표현이 동일하거나 실질적으로 유사해야 한다(실질적 유사성). 일반적으로 온라인 게임은 어문, 음악, 미술, 영상, 컴퓨터프로그램 등이 결합되어 있는 복합적 성격의 저작물이다. 이 가운데 추상적인 게임의 장르, 기본적인 배경, 전개방식, 규칙, 단계변화 등은 게임의 개념ㆍ방식ㆍ해법ㆍ창작도구로서 아이디어에 해당하여 저작권법에 의한 보호를 받을 수 없다. 그러나 최근 게임 저작물 관련 분쟁 사안에서 법원은 “게임 저작물의 창작성 여부를 판단할 때에는 게임물을 구성하는 구성요소들 각각의 창작성을 고려함은 물론이고, 구성요소들이 일정한 제작 의도와 시나리오에 따라 기술적으로 구현되는 과정에서 선택ㆍ배열되고 조합됨에 따라 전체적으로 어우러져 그 게임물 자체가 다른 게임물과 구별되는 창작적 개성을 가지고 저작물로서 보호를 받을 정도에 이르렀는지도 고려해야 한다.”라고 판시하고 있다. 기존 하급심 판례(‘봄버맨’)에서 ‘게임의 장르, 기본적인 게임의 배경, 게임의 전개방식, 규칙, 게임의 단계변화 등’은 게임의 개념ㆍ방식ㆍ해법ㆍ창작도구로서 ‘아이디어’로 분류하고 ‘게임 화면상의 플레이필드 및 맵과 블록의 구체적인 구성과 형태, 캐릭터의 형태, 폭탄 및 화염의 형태, 각종 아이템의 형태 등’의 구성요소들 각각의 창작성만을 고려한 것과는 대비되는 판단이다. 즉 게임물을 구성하는 개별 요소들의 창작성은 물론 이러한 구성요소들의 전체적인 어우러짐에 있어 다른 게임물과 구별되는 창작성이 드러나는지 여부도 함께 살피고 있는 것이다. 이처럼 저작권 침해 분쟁에 있어 ‘아이디어와 표현’의 경계는 일률적으로 명확히 구분하여 적용할 수 없고 사안마다 개별적으로 살펴야 하는 것이므로 온라인 게임 개발 시 이러한 대법원의 판단 내용을 염두에 둘 필요가 있을 것이다. ● 대법원 2019. 6. 27. 선고 2017다212095 판결(‘팜히어로사가’).매치-3-게임(match-3-game) 형식의 두 모바일 게임의 저작권 침해 사안에서 법원은 “甲 회사의 게임물은 개발자가 축적된 게임 개발 경험과 지식을 바탕으로 게임물의 성격에 비추어 필요하다고 판단된 요소들을 선택하여 나름대로의 제작 의도에 따라 배열ㆍ조합함으로써, 개별 구성요소의 창작성 인정 여부와 별개로 특정한 제작 의도와 시나리오에 따라 기술적으로 구현된 주요한 구성요소들이 선택ㆍ배열되고 유기적인 조합을 이루어 선행 게임물과 확연히 구별되는 창작적 개성을 갖추고 있으므로 저작물로서 보호 대상이 될 수 있고, 乙회사의 게임물은 甲 회사의 게임물 제작 의도와 시나리오가 기술적으로 구현된 주요한 구성요소들의 선택과 배열 및 유기적인 조합에 따른 창작적인 표현형식을 그대로 포함하고 있으므로, 양 게임물은 실질적으로 유사하다고 볼 수 있다.”라고 판시하며 침해를 인정하였다.

[질문]
저작권 보호 대상이 되는 저작물의 요건은 무엇인가?

[답변 형식]
- 핵심 답변
- 근거 조문/판례
- Source

- 핵심 답변
저작권 보호 대상이 되는 저작물은 **‘인간의 사상 또는 감정을 표현한 창작물’**이어야 하며(창작성 있는 **표현형식**), **아이디어·이론 등 표현 그 자체가 아닌 내용은 원칙적으로 보호 대상이 아닙니다**. 또한 **‘사실의 전달에 불과한 시사보도’**는 보호받지 못합니다.

- 근거 조문/판례
  - **저작권법 제2조 제1호**: 저작물 = “인간의 사상 또는 감정을 표현한 창작물” (Source 4)
  - **대법원 94도2238**: 창작성은 완전한 독창성이 아니라 **단순 모방이 아닌 저작자 자신의 독자적인 사상·감정의 표현**이면 족함 (저작권법 **제2조 제1호**) (Source 3)
  - **대법원 2011도3599**: 저작권 보호는 **창작적인 표현형식**에 미치며, **아이디어·이론 등 사상/감정 자체는 원칙적으로 보호 대상 아님** (Source 1)
  - **저작권법 제7조 제5호**: “**사실의 전달에 불과한 시사보도**”는 보호받지 못하는 저작물 (Source 4)

- Source
Source 1 (2011도3599), Source 3 (94도2238), Source 4 (QA-17)

## Runtime: Step4. 답변 출력

In [24]:
import langchain
langchain.debug = True

answer, context = generate_answer(query, selected_docs, mode_name=ACTIVE_MODE)

print(f"질문: {query}")
print(f"\n답변:\n{answer}")

INFO | final context | mode=case_plus_qa | chars=9918
INFO | final context preview | [Source 1] case_number=2011도3599 | document_type=case_law | article=제5조 | ho=제1항 【주 문】상고를 모두 기각한다. 이    유 상고이유를 판단한다. 1. 저작권법 제5조 제1항 은 ‘원저작물을 번역·편곡·변형·각색·영상제작 그 밖의 방법으로 작성한 창작물’을 ‘2차적저작물’이라고 규정하고 있는바, 2차적저작물이 되기 위해서는 원저작물을 기초로 수정·증감이 가해지되 원저작물과 실질적 유사성을 유지하여야 한다. 따라서 어문저작물인 원저작물을 기초로 하여 이를 요약한 요약물이 원저작물과 실질적인 유사성이 없는 별개의 독립적인 새로운 저작물이 된 경우에는 원저작물 저작권자의 2차적저작물작성권을 침해한 것으로 되지는 아니하는데 ( 대법원 2010. 2. 11. 선고 2007다63409 판결 등 참조), 여기서 요약물이 그 원저작물과 사이에 실질적인 유사성이 있는지 여부는, 요약물이 원저작물의 기본으로 되는 개요, 구조, 주된 구성 등을 그대로 유지하고 있는지 여부, 요약물이 원저작물을 이루는 문장들 중 일부만을 선택하여 발췌한 것이거나 발췌한 문장들의 표현을 단순히 단축한 정도에 불과한지 여부, 원저작물과 비교한 요약물의 상대적인 분량, 요약물의 원저작물에 대한 대체가능성 여부 등을 종합적으로 고려하여 판단해야 한다. 한편 저작권의 보호 대상은 인간의 사상 또는 감정을 말, 문자, 음, 색 등에 의하여 구체적으로 외부에 표현한 창작적인 표현형식이고, 거기에 표현되어 있는 내용 즉 아이디어나 이론 등의 사상 또는 감정 그 자체는 원칙적으로 저작권의 보호 대상이 아니므로, 저작권의 침해 여부를 가리기 위하여 두 저작물 사이에 실질적인 유사성이 있는지 여부를 판단함에 있어서도 창작적인 표현형식에 해당하는 것만을 가지고 대비해 보아야 하고, 표현형식이 아닌 사상 또는 감정 그 자체에 독창성·신규성이 있는지를 고려하여서는 안 된다( 대법원 2011. 2. 10. 선고 2009도291 판결 등 참조).  [Source 2] case_number=2009도6073 | document_type=case_law | article=제4조 | ho=제1항 【주 문】  원심판결을 파기하고, 사건을 서울중앙지방법원에 환송한다.  이 유  상고이유를 판단한다.  구 저작권법(2006. 12. 28. 법률 제8101호로 전문 개정되기 전의 것, 이하 같다) 제4조 제1항 제8호  는 "지도, 도표, 설계도, 약도, 모형 그 밖의 도형저작물"을 저작물의 하나로 예시하고 있는데, 이와 같은 도형저작물은 예술성의 표현보다는 기능이나 실용적인 사상의 표현을 주된 목적으로 하는 이른바 기능적 저작물로서, 기능적 저작물은 그 표현하고자 하는 기능 또는 실용적인 사상이 속하는 분야에서의 일반적인 표현방법, 규격 또는 그 용도나 기능 자체, 저작물 이용자의 이해의 편의성 등에 의하여 그 표현이 제한되는 경우가 많으므로 작성자의 창조적 개성이 드러나지 않을 가능성이 크지만, 기능적 저작물도 구 저작권법의 보호대상이 되기 위해서

질문: 저작권 보호 대상이 되는 저작물의 요건은 무엇인가?

답변:
- 핵심 답변
저작권법상 보호 대상이 되는 저작물이 되려면 **① ‘인간의 사상 또는 감정’을 ② ‘표현한’ ③ ‘창작물’**이어야 합니다. 또한 여기서 말하는 창작성이란 **완전한 독창성까지 요구되는 것은 아니고**, **단순 모방이 아닌 저작자 자신의 독자적인 사상 또는 감정의 표현**이 담겨 **기존 작품과 구별될 정도**이면足합니다. (아이디어 자체가 아니라 **창작적인 표현형식**이 보호 대상입니다.)

- 근거 조문/판례
  - **저작권법 제2조 제1호**: “저작물”은 **인간의 사상 또는 감정을 표현한 창작물**
  - **대법원 1994. 12. 2. 선고 94도2238 판결**: 창작성은 완전한 독창성이 아니라 **단순 모방이 아니고 저작자 자신의 독자적인 사상 또는 감정의 표현**을 담아 **구별 가능**하면 충분
  - **대법원 2011. 4. 28. 선고 2011도3599 판결**: 저작권 보호는 **창작적인 표현형식**에 미치며 **아이디어·이론 등 내용 자체는 원칙적으로 보호 대상이 아님**

- Source
  - Source 4 (저작권법 제2조)
  - Source 3 (94도2238)
  - Source 1 (2011도3599)

## RAG 성능 평가

In [25]:
from ragas import EvaluationDataset, evaluate
from ragas.llms import LangchainLLMWrapper
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness

eval_sample_size = min(10, len(qa_eval_df))
eval_sample_df = qa_eval_df[["Q", "A"]].head(eval_sample_size).copy()
eval_sample_df.columns = ["question", "reference"]

print(f"RAGAS 평가 질문 수: {len(eval_sample_df)}")
eval_sample_df.head()

RAGAS 평가 질문 수: 10

/var/folders/5b/_vr668qd1qjfth5qbkggmk0m0000gn/T/ipykernel_52576/3220518135.py:3: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness
/var/folders/5b/_vr668qd1qjfth5qbkggmk0m0000gn/T/ipykernel_52576/3220518135.py:3: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness
/var/folders/5b/_vr668qd1qjfth5qbkggmk0m0000gn/T/ipykernel_52576/3220518135.py:3: DeprecationWarning: Importing FactualCorrectness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import FactualCorrectness
  from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness

,question,reference
21,"연예인의 이름을 상업적 행위에 이용할 경우, 손해배상책임을 지나요?",유명 연예인이나 운동선수 등은 자신의 성명이나 초상을 상업적으로 이용할 수 있는 권...
22,다른 사람이 나의 저작물을 패러디하였는데 저작권 침해에 해당하는 것일까요?,"저작권법상 허용되는 패러디에 대한 판단 기준이 명확하지는 않으나, 기존의 저작물에 ..."
23,사진이나 영상에 연예인의 유행어를 이용하는 것도 침해에 해당하는 것일까요?,짧은 유행어를 이용하는 경우는 저작권 침해로 보기는 어렵지만 퍼블리시티권 침해에 해...
24,"이미 사망한 유명인을 모델로 하여 영화나 드라마를 제작하려고 하는데, 유족의 허락을...",사망한 유명인의 초상이나 성명을 상업적으로 이용하는 것은 퍼블리시티권과 관련하여 법...
25,저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경할 경우 동일성유지...,저작자가 명시적으로 동의한 범위 내에서 저작물을 변경하는 것은 아무런 문제가 되지 ...

In [26]:
def answer_with_rag(question, mode_name: str = ACTIVE_MODE):
    retrieval_result = retrieve_candidates(question, mode_name=mode_name, verbose=False)
    selected_docs = rerank_documents(question, retrieval_result["documents"], mode_name=mode_name)
    response, _ = generate_answer(question, selected_docs, mode_name=mode_name)
    return {
        "mode": mode_name,
        "user_input": question,
        "retrieved_contexts": [doc.page_content for doc in selected_docs],
        "response": response,
    }

In [27]:
def evaluate_ragas(eval_frame, mode_name: str, sample_size=eval_sample_size):
    eval_samples = []
    for row in eval_frame.head(sample_size).itertuples(index=False):
        result = answer_with_rag(row.question, mode_name=mode_name)
        result["reference"] = row.reference
        eval_samples.append(result)
    evaluation_dataset = EvaluationDataset.from_list(eval_samples)
    print(f"[{mode_name}] 평가 데이터셋 생성 완료: {len(eval_samples)}건")
    return evaluation_dataset

evaluation_datasets = {
    mode: evaluate_ragas(eval_sample_df, mode_name=mode)
    for mode in ["case_only", "case_plus_qa"]
}

Batches: 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]
INFO | reranked results [case_only] | count=5
INFO | reranked results [case_only] #1 | case=2012도13718 | type=case_law | article=['20', '21', '307', '37'] | preview=사건명: 명예훼손(일부예비적죄명:모욕)·저작권법위반 법원: 대법원 선고일: 2014.09.04 사건번호: 2012도13718
INFO | reranked results [case_only] #2 | case=96다2460 | type=case_law | article=['5', '64'] | preview=사건명: 손해배상(자) 법원: 대법원 선고일: 1997.05.28 사건번호: 96다2460
INFO | reranked results [case_only] #3 | case=98다41216 | type=case_law | article=['91', '93', '95', '97'] | preview=사건명: 손해배상(지) 법원: 대법원 선고일: 1999.05.25 사건번호: 98다41216
INFO | reranked results [case_only] #4 | case=2002다18244 | type=case_law | article=['93'] | preview=사건명: 손해배상(지) 법원: 대법원 선고일: 2004.06.11 사건번호: 2002다18244
INFO | reranked results [case_only] #5 | case=2004다18736 | type=case_law | article=['5'] | preview=사건명: 손해배상(지) 법원: 대법원 선고일: 2004.07.08 사건번호: 2004다18736
INFO | final context | mode=case_only | chars=744
INFO | final context preview | [Source 1] case_number=2012도13718 | document_type=case_law | article=제20조, 제21조, 제307조, 제37조 | ho=제1항, 제2항 사건명: 명예훼손(일부예비적죄명:모욕)·저작권법위반 법원: 대법원 선고일: 2014.09.04 사건번호: 2012도13718  [Source 2] case_number=96다2460 | document_type=case_law | article=제5조, 제64조 | ho=제2항 사건명: 손해배상(자) 법원: 대법원 선고일: 1997.05.28 사건번호: 96다2460  [Source 3] case_number=98다41216 | document_type=case_law | article=제91조, 제93조, 제95조, 제97조 | ho=항 정보 없음 사건명: 손해배상(지) 법원: 대법원 선고일: 1999.05.25 사건번호: 98다41216  [Source 4] case_number=2002다18244 | document_type=case_law | article=제93조 | ho=제2항 사건명: 손해배상(지) 법원: 대법원 선고일: 2004.06.11 사건번호: 2002다18244  [Source 5] case_number=2004다18736 | document_type=case_law | article=제5조 | ho=제1항 사건명: 손해배상(지) 법원: 대법원 선고일: 2004.07.08 사건번호: 2004다18736
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.27s/it]
INFO | reranked results [case_only] | count=5
INFO | reranked results [case_only] #1 | case=2012다73493,73509 | type=case_law | article=None | preview=【주 문】상고를 기각한다.  상고비용은 피고(반소원고)가 부담한다. 이    유 상고이유를 판단한다. 1. 상고이유 제1점 및 제2점에 대하여 다른 사람의 저작물을 무단히 복제하게 되면 복제권의 침해가 되고 이 경우 저작물을 원형 그대로 복제하지 아니하고 다소의 수정·증감이나 변경이 가
INFO | reranked results [case_only] #2 | case=89다카12824 | type=case_law | article=['10', '11', '12', '13', '16', '95'] | preview= 상고이유를 본다. 제1점에 대하여, 저작자는 저작권법 제10조에 의하여 저작인격권과 저작재산권을 가지는 것이고 저작인격권에는 공표권( 제11조), 성명표시권( 제12조), 동일성유지권( 제13조)이 포함되는 것이며 저작재산권에는 복제권등이 포함되는 것이다( 제16조 내지 제12조).
INFO | reranked results [case_only] #3 | case=2010다79923 | type=case_law | article=['13', '26', '47'] | preview=【주 문】상고를 모두 기각한다.  상고비용은 원고들이 부담한다. 이    유 상고이유를 판단한다. 1. 저작자는 그의 저작물의 내용·형식 및 제호의 동일성을 유지할 권리를 가지는데( 저작권법 제13조 제1항 ), 저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경한 경우에
INFO | reranked results [case_only] #4 | case=2011도3599 | type=case_law | article=['5'] | preview=【주 문】상고를 모두 기각한다. 이    유 상고이유를 판단한다. 1. 저작권법 제5조 제1항 은 ‘원저작물을 번역·편곡·변형·각색·영상제작 그 밖의 방법으로 작성한 창작물’을 ‘2차적저작물’이라고 규정하고 있는바, 2차적저작물이 되기 위해서는 원저작물을 기초로 수정·증감이 가해지되 원
INFO | reranked results [case_only] #5 | case=97마330 | type=case_law | article=None | preview=결국 저작권의 보호 대상은 아이디어가 아닌 표현에 해당하고 저작자의 독창성이 나타난 개인적인 부분에 한하므로, 저작권의 침해 여부를 가리기 위하여 두 저작물 사이에 실질적인 유사성이 있는가의 여부를 판단함에 있어서도 표현에 해당하는 부분만을 가지고 대비하여야 한다  (  당원 1993.
INFO | final context | mode=case_only | chars=7103
INFO | final context preview | [Source 1] case_number=2012다73493,73509 | document_type=case_law | article=조문 정보 없음 | ho=항 정보 없음 【주 문】상고를 기각한다.  상고비용은 피고(반소원고)가 부담한다. 이    유 상고이유를 판단한다. 1. 상고이유 제1점 및 제2점에 대하여 다른 사람의 저작물을 무단히 복제하게 되면 복제권의 침해가 되고 이 경우 저작물을 원형 그대로 복제하지 아니하고 다소의 수정·증감이나 변경이 가하여진 것이라고 하더라도 새로운 창작성을 더하지 아니한 정도이면 복제로 보아야 한다. 그리고 저작권법이 보호하는 것은 인간의 사상 또는 감정을 말·문자·음·색 등에 의하여 구체적으로 외부에 표현하는 창작적인 표현형식이므로, 복제권 또는 2차적저작물작성권의 침해 여부를 가리기 위하여 두 저작물 사이에 실질적 유사성이 있는가의 여부를 판단함에 있어서는 창작적인 표현형식에 해당하는 것만을 가지고 대비하여야 한다 ( 대법원 2010. 2. 11. 선고 2007다63409 판결 등 참조). 또한 저작권법이 보호하는 복제권의 침해가 있다고 하기 위하여는 침해되었다고 주장되는 기존의 저작물과 대비대상이 되는 저작물 사이에 실질적 유사성이 있다는 점 이외에도 대상 저작물이 기존의 저작물에 의거하여 작성되었다는 점이 인정되어야 한다. 이때 대상 저작물이 기존의 저작물에 의거하여 작성되었다는 사실이 직접 인정되지 아니하더라도 기존의 저작물에 대한 접근가능성, 대상 저작물과 기존의 저작물 사이에 실질적 유사성 등의 간접사실이 인정되면 대상 저작물이 기존의 저작물에 의거하여 작성되었다는 점은 사실상 추정된다 ( 대법원 2007. 12. 13. 선고 2005다35707 판결 참조). 그리고 대상 저작물이 기존의 저작물에 의거하여 작성되었는지 여부와 양 저작물 사이에 실질적 유사성이 있는지 여부는 서로 별개의 판단으로서, 전자의 판단에는 후자의 판단과 달리 저작권법에 의하여 보호받는 표현뿐만 아니라 저작권법에 의하여 보호받지 못하는 표현 등이 유사한지 여부도 함께 참작될 수 있다 ( 대법원 2007. 3. 29. 선고 2005다44138 판결 참조).  [Source 2] case_number=89다카12824 | document_type=case_law | article=제10조, 제11조, 제12조, 제13조, 제16조 | ho=항 정보 없음  상고이유를 본다. 제1점에 대하여, 저작자는 저작권법 제10조에 의하여 저작인격권과 저작재산권을 가지는 것이고 저작인격권에는 공표권( 제11조), 성명표시권( 제12조), 동일성유지권( 제13조)이 포함되는 것이며 저작재산권에는 복제권등이 포함되는 것이다( 제16조 내지 제12조). 그러므로 다른 사람의 저작물을 원저작자의 이름으로 무단히 복제하게 되면 복제권의 침해가 되는 것이고 이 경우 저작물을 원형 그대로 복제하지 아니하고 다소의 수정증감이나 변경이 가하여진 것이라고 하더라도 원저작물의 재제 또는 동일성이 인식되거나 감지되는 정도이면 복제로 보아야 할 것이며 원
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.31s/it]
INFO | reranked results [case_only] | count=5
INFO | reranked results [case_only] #1 | case=2021다219116 | type=case_law | article=['10'] | preview= 상고이유를 판단한다. 1. 원심판결 이유 및 기록에 의하면 다음과 같은 사실을 알 수 있다. 가. 원고는 2016. 6.경 목걸이, 귀걸이 등 장신구의 온라인 판매업을 영위하는 피고와 사이에, 원고를 모델로 하고 피고를 촬영자로 하는 촬영계약(이하 ‘이 사건 촬영계약’이라고 한다)을
INFO | reranked results [case_only] #2 | case=2020도10180 | type=case_law | article=['136'] | preview=【주 문】  상고를 기각한다.  이 유  상고이유를 판단한다.  1.  저작권법 제136조 제2항 제1호  는 저작인격권 또는 실연자의 인격권을 침해하여 저작자 또는 실연자의 명예를 훼손한 사람을 처벌하도록 규정하고 있다. 위 규정에서 정한 저작권법위반죄는 저작인격권 또는 실연자의 인격
INFO | reranked results [case_only] #3 | case=2005도7673 | type=case_law | article=['10'] | preview=사건명: 저작권법위반 법원: 대법원 선고일: 2006.02.24 사건번호: 2005도7673  판례내용: 1. 양벌규정에 의한 영업주의 처벌에 관하여양벌규정에 의한 영업주의 처벌은 금지위반행위자인 종업원의 처벌에 종속하는 것이 아니라 독립하여 그 자신의 종업원에 대한 선임감독상의 과실로
INFO | reranked results [case_only] #4 | case=2010다20044 | type=case_law | article=['2'] | preview=( 대법원 2008. 10. 17.자 2006마342 결정 참조). 위 법리와 기록에 비추어 살펴보면, 원심이 그 판시와 같은 사정을 들어 피고 제품이 원고들 상품과 실질적으로 동일한 형태라고 할 수 없으므로 부정경쟁방지법 제2조 제1호 (자)목에 해당하지 않는다는 취지로 판단한 것은
INFO | reranked results [case_only] #5 | case=2012도10777 | type=case_law | article=['25'] | preview= 상고이유를 판단한다. 1. 원심은, 피고인들이 2002년 한·일월드컵 당시 널리 사용된 “Be The Reds!”라는 응원문구를 도안화한 원심 판시 저작물 (이하 ‘이 사건 저작물’이라 한다)이 그려진 티셔츠 등을 착용한 모델을 촬영한 원심 판시 사진들(이하 ‘이 사건 사진들’이라 한
INFO | final context | mode=case_only | chars=10993
INFO | final context preview | [Source 1] case_number=2021다219116 | document_type=case_law | article=제10조 | ho=항 정보 없음  상고이유를 판단한다. 1. 원심판결 이유 및 기록에 의하면 다음과 같은 사실을 알 수 있다. 가. 원고는 2016. 6.경 목걸이, 귀걸이 등 장신구의 온라인 판매업을 영위하는 피고와 사이에, 원고를 모델로 하고 피고를 촬영자로 하는 촬영계약(이하 ‘이 사건 촬영계약’이라고 한다)을 체결하였다. 원고는 2016. 7. 29.부터 2017. 6. 1.까지 9회에 걸쳐 피고가 판매하는 장신구를 목, 귀, 손, 팔 등에 착용하여 장신구가 부각될 수 있는 자세를 취한 상반신 사진들을 촬영하였고 피고로부터 모두 405만 원을 받았다. 촬영한 사진들 중 원고가 이 사건에서 초상권 침해를 주장하는 사진(이하 ‘이 사건 사진’이라고 한다)만 1,000장을 상회하는데, 대부분 원고의 얼굴을 포함하고 있거나 피사체가 원고임을 식별할 수 있다. 나. 이 사건 촬영계약은 촬영한 사진의 저작권 및 사용권이 피고에게 있고 피고가 해당 상품의 촬영본을 인터넷에 게시, 인화, 전시 및 출판할 수 있다고 정하고 있으나, 촬영한 사진의 사용 기간에 대하여는 정하고 있지 않다. 다. 한편 이 사건 촬영계약은 이 사건 사진의 초상권은 원고에게 있다고 명시하고 있고, 촬영본의 제3자에 대한 상업적인 제공 및 2차 가공은 불가능하며 상업적 활용 및 제3자에 대한 제공이 필요할 경우 원고와 피고가 상호 협의하여야 한다고 정하고 있다. 라. 원고는 2017. 6. 22. 연예매니지먼트 회사와 연예인 전속계약을 체결하였고, 2018. 11. 28. 피고에게 이 사건 촬영계약의 해지를 통보하는 한편 이 사건 사진에 대한 사용 허락을 철회한다고 밝히면서 이 사건 사진사용의 중지를 요청하였다. 2. 원심은 판시와 같은 이유로, 원고가 피고에게, 피고가 해당 상품을 판매하는 동안에는 기간의 제한 없이 이 사건 사진을 상업적으로 사용하는 것을 허용하였다고 보아야 하므로 이 사건 사진사용이 원고의 초상권을 침해하였다는 원고의 주장은 이유 없다는 취지로 판단하였다. 3. 그러나 원심의 판단은 다음과 같은 이유로 수긍하기 어렵다. 가. 사람은 누구나 자신의 얼굴 기타 사회통념상 특정인임을 식별할 수 있는 신체적 특징에 관하여 함부로 촬영 또는 그림묘사되거나 공표되지 아니하며 영리적으로 이용당하지 않을 권리를 가지는데, 이러한 초상권은 헌법 제10조에 의하여 헌법적으로도 보장되고 있는 권리이다. 따라서 타인의 얼굴 기타 사회통념상 특정인임을 식별할 수 있는 신체적 특징이 나타나는 사진을 촬영하거나 공표하고자 하는 사람은 피촬영자로부터 촬영에 관한 동의를 받고 사진을 촬영하여야 하고, 사진촬영에 관한 동의를 받았다 하더라도 사진촬영에 동의하게 된 동기 및 경위, 사진의 공표에 의하여 달성하려는 목적, 거래관행, 당사자의 지식, 경험 및 경제적 지위, 수수된 급부가 균형을 유지하고 있는지 여부, 사진촬영 당시 당해 공표방법이 예견 가능하였는지
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.28s/it]
INFO | reranked results [case_only] | count=5
INFO | reranked results [case_only] #1 | case=2018도2844 | type=case_law | article=['19', '88', '1', '21', '10', '17', '308', '14', '5'] | preview=형법 제308조 , 저작자 사망 후의 저작인격권 보호에 관한 저작권법 제14조 제2항 , 사망한 사람의 인격권에 대한 침해 금지와 그에 대한 구제절차를 정하고 있는 언론중재 및 피해구제 등에  관한 법률 제5조의2는 이 점을 명시한 규정이다. 위와 같은 형벌법규 해석에 관한 일반적인 법
INFO | reranked results [case_only] #2 | case=2018도2844 | type=case_law | article=['19', '88', '1', '21', '10', '17', '308', '14', '5'] | preview=구 의료법 제19조 에서 누설을 금지하고 있는 ‘다른 사람의 비밀’은 당사자의 동의 없이는 원칙적으로 공개되어서는 안 되는 비밀영역으로 보호되어야 한다. 이러한 보호의  필요성은 환자가 나중에 사망하더라도 소멸하지 않는다. 구 의료법 제21조 제1항은 환자가 사망하였는지 여부를 묻지 않
INFO | reranked results [case_only] #3 | case=2018도2844 | type=case_law | article=['19', '88', '1', '21', '10', '17', '308', '14', '5'] | preview=, 대법원 2017. 12. 7. 선고 2017도10122 판결 등 참조). 형벌법규에서 ‘타인’이나 ‘다른 사람’이 반드시 생존하는 사람만을 의미하는 것은 아니고  형벌법규가  보호하고자  하는  법익과  법문의  논리적  의미를  분명히  밝히는  체계적·논리적 해석을 통하여 사망한
INFO | reranked results [case_only] #4 | case=2006도4126 | type=case_law | article=[] | preview=【주 문】원심판결을 파기하고, 사건을 서울중앙지방법원 합의부에 환송한다. 이    유 상고이유를 본다. 원심은 그 판시와 같은 사실을 인정한 다음,          공소외인과          피고인 1 사이의 1996. 6. 26.자 이 사건 합의서 제3항에서 원심 판시 이 사건 기존
INFO | reranked results [case_only] #5 | case=97후860,877,884 | type=case_law | article=['7', '12', '96', '14'] | preview=에 해당한다고 봄이 상당하다  .  그리고  이러한 경우에 그 저명한 화가가 생존해 있었더라면 자신의 저작물임을 나타내기 위하여 표시해 오던 서명을 타인이 자신과 전혀 무관한 상품의 상표로 무단 등록하여 공표하고 사용하는 것은 저명한 미술저작자로서의 인격권을 침해하는 불법행위에 해당한다
INFO | final context | mode=case_only | chars=4525
INFO | final context preview | [Source 1] case_number=2018도2844 | document_type=case_law | article=제19조, 제88조, 제1조, 제21조, 제10조 | ho=제1항, 제2항 형법 제308조 , 저작자 사망 후의 저작인격권 보호에 관한 저작권법 제14조 제2항 , 사망한 사람의 인격권에 대한 침해 금지와 그에 대한 구제절차를 정하고 있는 언론중재 및 피해구제 등에  관한 법률 제5조의2는 이 점을 명시한 규정이다. 위와 같은 형벌법규 해석에 관한 일반적인 법리, 의료법의 입법취지, 구 의료법 제19조 의 문언·내용·체계·목적 등에 비추어 보면, 구 의료법 제19조 에서 정한 ‘다른 사람’에는 생존하는 개인 이외에 이미 사망한 사람도 포함된다고 보아야 한다. 다. 원심판결 이유를 위에서 본 법리와 적법하게 채택된 증거에 비추어 살펴보면, 이  부분 공소사실이 유죄로 인정된다는 원심의 판단에 상고이유 주장과 같이 논리와 경험의 법칙에 반하여 자유심증주의의 한계를 벗어나거나 구 의료법 제19조 에 관한 법리를  오해한 잘못이 없다. 3. 결론 피고인의 상고는 이유 없어 이를 기각하기로 하여, 대법관의 일치된 의견으로 주문과 같이 판결한다.  [Source 2] case_number=2018도2844 | document_type=case_law | article=제19조, 제88조, 제1조, 제21조, 제10조 | ho=제1항, 제2항 구 의료법 제19조 에서 누설을 금지하고 있는 ‘다른 사람의 비밀’은 당사자의 동의 없이는 원칙적으로 공개되어서는 안 되는 비밀영역으로 보호되어야 한다. 이러한 보호의  필요성은 환자가 나중에 사망하더라도 소멸하지 않는다. 구 의료법 제21조 제1항은 환자가 사망하였는지 여부를 묻지 않고 환자가 아닌 다른 사람에게 환자에 관한 기록을  열람하게 하거나 사본을 내주는 등 내용을 확인할 수 있게 해서는 안 된다고 정하고  있는데,  이 점을  보더라도 환자가  사망했다고 해서  보호 범위에서  제외된다고 볼  수  없다. 헌법 제10조 는 인간의 존엄과 가치를 선언하고 있고, 헌법 제17조 는 사생활의 비밀과 자유를 보장하고 있다. 따라서 모든 국민은 자신에 관한 정보를 스스로 통제할 수  있는 자기결정권과 사생활이 함부로 공개되지 않고 사적 영역의 평온과 비밀을 요구할  수 있는 권리를 갖는다( 대법원 1998. 7. 24. 선고 96다42789 판결 , 대법원 1998. 9. 4.  선고 96다11327 판결 , 대법원 2014. 7. 24. 선고 2012다49933 판결 등 참조). 이와 같은 개인의 인격적 이익을 보호할 필요성은 그의 사망으로 없어지는 것이 아니다. 사람의 사망 후에 사적 영역이 무분별하게 폭로되고 그의 생활상이 왜곡된다면 살아있는  동안  인간의 존엄과  가치를 보장하는  것이 무의미해질  수 있다.  사람은 적어도  사망  후에 인격이 중대하게 훼손되거나 자신의 생활상이 심각하게 왜곡되지 않을 것이라고  신뢰하고 그러한 기대 속에서 살 수 있는 경우에만 인간으로서의 존
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]
INFO | reranked results [case_only] | count=5
INFO | reranked results [case_only] #1 | case=2010다79923 | type=case_law | article=['13', '26', '47'] | preview=【주 문】상고를 모두 기각한다.  상고비용은 원고들이 부담한다. 이    유 상고이유를 판단한다. 1. 저작자는 그의 저작물의 내용·형식 및 제호의 동일성을 유지할 권리를 가지는데( 저작권법 제13조 제1항 ), 저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경한 경우에
INFO | reranked results [case_only] #2 | case=2010다79923 | type=case_law | article=['13', '26', '47'] | preview= 상고이유를 판단한다. 1. 저작자는 그의 저작물의 내용·형식 및 제호의 동일성을 유지할 권리를 가지는데( 저작권법 제13조 제1항), 저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경한 경우에는 저작자의 위와 같은 동일성유지권 침해에 해당하지 아니한다 ( 대법원 199
INFO | reranked results [case_only] #3 | case=89다카12824 | type=case_law | article=['10', '11', '12', '13', '16', '95'] | preview= 상고이유를 본다. 제1점에 대하여, 저작자는 저작권법 제10조에 의하여 저작인격권과 저작재산권을 가지는 것이고 저작인격권에는 공표권( 제11조), 성명표시권( 제12조), 동일성유지권( 제13조)이 포함되는 것이며 저작재산권에는 복제권등이 포함되는 것이다( 제16조 내지 제12조).
INFO | reranked results [case_only] #4 | case=98다41216 | type=case_law | article=['91', '93', '95', '97'] | preview= 상고이유를 본다.공동저작물에 관한 권리가 침해된 경우에 각 저작자 또는 각 저작재산권자는 다른 저작자 또는 다른 저작재산권자의 동의 없이 저작권법 제91조의 규정에 의한 저작권 등의 침해행위금지청구를 할 수 있고, 같은 법 제93조에 의하여 저작인격권을 제외한 저작재산권의 침해에 관하
INFO | reranked results [case_only] #5 | case=2010다79923 | type=case_law | article=['13', '26', '47'] | preview=사건명: 저작인격권 침해 정지 법원: 대법원 선고일: 2013.04.26 사건번호: 2010다79923
INFO | final context | mode=case_only | chars=9562
INFO | final context preview | [Source 1] case_number=2010다79923 | document_type=case_law | article=제13조, 제26조, 제47조 | ho=제1항, 제6항 【주 문】상고를 모두 기각한다.  상고비용은 원고들이 부담한다. 이    유 상고이유를 판단한다. 1. 저작자는 그의 저작물의 내용·형식 및 제호의 동일성을 유지할 권리를 가지는데( 저작권법 제13조 제1항 ), 저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경한 경우에는 저작자의 위와 같은 동일성유지권 침해에 해당하지 아니한다 ( 대법원 1992. 12. 24. 선고 92다31309 판결 등 참조). 그리고 저작물에 대한 출판계약을 체결한 저작자가 저작물의 변경에 대하여 동의하였는지 여부 및 동의의 범위는 출판계약의 성질·체결 경위·내용, 계약 당사자들의 지위와 상호관계, 출판의 목적, 출판물의 이용실태, 저작물의 성격 등 제반 사정을 종합적으로 고려하여 구체적·개별적으로 판단하여야 한다. 한편 행정처분이 아무리 위법하다고 하여도 그 하자가 중대하고 명백하여 당연 무효라고 보아야 할 사유가 있는 경우를 제외하고는 아무도 그 하자를 이유로 무단히 그 효과를 부정하지 못하는 것이므로 ( 대법원 2010. 4. 29. 선고 2007다12012 판결 등 참조), 저작자가 출판계약에서 행정처분을 따르는 범위 내에서의 저작물 변경에 동의한 경우에는, 설사 행정처분이 위법하더라도 당연 무효라고 보아야 할 사유가 있다고 할 수 없는 이상 그 행정처분에 따른 계약 상대방의 저작물 변경은 저작자의 동일성유지권 침해에 해당하지 아니한다. 2. 위 법리에 비추어 살펴본다. 가. 원심판결 이유와 기록에 의하면, 다음과 같은 사실들을 알 수 있다.  [Source 2] case_number=2010다79923 | document_type=case_law | article=제13조, 제26조, 제47조 | ho=제1항, 제6항  상고이유를 판단한다. 1. 저작자는 그의 저작물의 내용·형식 및 제호의 동일성을 유지할 권리를 가지는데( 저작권법 제13조 제1항), 저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경한 경우에는 저작자의 위와 같은 동일성유지권 침해에 해당하지 아니한다 ( 대법원 1992. 12. 24. 선고 92다31309 판결 등 참조). 그리고 저작물에 대한 출판계약을 체결한 저작자가 저작물의 변경에 대하여 동의하였는지 여부 및 동의의 범위는 출판계약의 성질·체결 경위·내용, 계약 당사자들의 지위와 상호관계, 출판의 목적, 출판물의 이용실태, 저작물의 성격 등 제반 사정을 종합적으로 고려하여 구체적·개별적으로 판단하여야 한다. 한편 행정처분이 아무리 위법하다고 하여도 그 하자가 중대하고 명백하여 당연 무효라고 보아야 할 사유가 있는 경우를 제외하고는 아무도 그 하자를 이유로 무단히 그 효과를 부정하지 못하는 것이므로( 대법원 2010. 4. 29. 선고 2007다12012 판결 등 참조), 저작자가 출판계약에서 행정처분을 따르는 범위 내에서의
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]
INFO | reranked results [case_only] | count=5
INFO | reranked results [case_only] #1 | case=2010다79923 | type=case_law | article=['13', '26', '47'] | preview=【주 문】상고를 모두 기각한다.  상고비용은 원고들이 부담한다. 이    유 상고이유를 판단한다. 1. 저작자는 그의 저작물의 내용·형식 및 제호의 동일성을 유지할 권리를 가지는데( 저작권법 제13조 제1항 ), 저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경한 경우에
INFO | reranked results [case_only] #2 | case=2012다73493,73509 | type=case_law | article=[] | preview=【주 문】상고를 기각한다.  상고비용은 피고(반소원고)가 부담한다. 이    유 상고이유를 판단한다. 1. 상고이유 제1점 및 제2점에 대하여 다른 사람의 저작물을 무단히 복제하게 되면 복제권의 침해가 되고 이 경우 저작물을 원형 그대로 복제하지 아니하고 다소의 수정·증감이나 변경이 가
INFO | reranked results [case_only] #3 | case=95다3381 | type=case_law | article=['5', '10', '52', '51'] | preview= 상고이유를 본다. 1. 타인의 원저작물을 번역한 창작물은 독자적인 저작물(2차적 저작물)로서 보호되고(저작권법 제5조), 저작물은 그 성질상 어떠한 절차나 형식의 이행을 필요로 하지 아니하고 저작한 때부터 당연히 발생하며(같은법 제10조 제2항), 저작재산권의 양도는 이를 등록하지 아
INFO | reranked results [case_only] #4 | case=2011도5835 | type=case_law | article=['35', '23', '28', '30'] | preview=원심이 같은 취지에서 피고인의 행위로 인하여 저작권자들의 저작권이 침해되지 않았다고 볼 수 없다고 판단한 것은 정당한 것으로 수긍할 수 있고, 거기에 상고이유의 주장과 같이 공정이용의 법리 등을 오해한 위법이 없다. 나. 사적 이용을 위한 복제에 관한 상고이유에 대하여 구 저작권법 제3
INFO | reranked results [case_only] #5 | case=94마2217 | type=case_law | article=['14'] | preview=그러나.  저작인격권은 저작재산권과는 달리 일신전속적인 권리로서 이를 양도하거나 이전할 수 없는 것이라 할 것이므로 비록 그 권한행사에 있어서는 이를 대리하거나 위임하는 것이 가능하다 할지라도 이는 어디까지나 저작인격권의 본질을 해하지 아니하는 한도 내에서만 가능하다 할 것이고 저작인격
INFO | final context | mode=case_only | chars=5097
INFO | final context preview | [Source 1] case_number=2010다79923 | document_type=case_law | article=제13조, 제26조, 제47조 | ho=제1항, 제6항 【주 문】상고를 모두 기각한다.  상고비용은 원고들이 부담한다. 이    유 상고이유를 판단한다. 1. 저작자는 그의 저작물의 내용·형식 및 제호의 동일성을 유지할 권리를 가지는데( 저작권법 제13조 제1항 ), 저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경한 경우에는 저작자의 위와 같은 동일성유지권 침해에 해당하지 아니한다 ( 대법원 1992. 12. 24. 선고 92다31309 판결 등 참조). 그리고 저작물에 대한 출판계약을 체결한 저작자가 저작물의 변경에 대하여 동의하였는지 여부 및 동의의 범위는 출판계약의 성질·체결 경위·내용, 계약 당사자들의 지위와 상호관계, 출판의 목적, 출판물의 이용실태, 저작물의 성격 등 제반 사정을 종합적으로 고려하여 구체적·개별적으로 판단하여야 한다. 한편 행정처분이 아무리 위법하다고 하여도 그 하자가 중대하고 명백하여 당연 무효라고 보아야 할 사유가 있는 경우를 제외하고는 아무도 그 하자를 이유로 무단히 그 효과를 부정하지 못하는 것이므로 ( 대법원 2010. 4. 29. 선고 2007다12012 판결 등 참조), 저작자가 출판계약에서 행정처분을 따르는 범위 내에서의 저작물 변경에 동의한 경우에는, 설사 행정처분이 위법하더라도 당연 무효라고 보아야 할 사유가 있다고 할 수 없는 이상 그 행정처분에 따른 계약 상대방의 저작물 변경은 저작자의 동일성유지권 침해에 해당하지 아니한다. 2. 위 법리에 비추어 살펴본다. 가. 원심판결 이유와 기록에 의하면, 다음과 같은 사실들을 알 수 있다.  [Source 2] case_number=2012다73493,73509 | document_type=case_law | article=조문 정보 없음 | ho=항 정보 없음 【주 문】상고를 기각한다.  상고비용은 피고(반소원고)가 부담한다. 이    유 상고이유를 판단한다. 1. 상고이유 제1점 및 제2점에 대하여 다른 사람의 저작물을 무단히 복제하게 되면 복제권의 침해가 되고 이 경우 저작물을 원형 그대로 복제하지 아니하고 다소의 수정·증감이나 변경이 가하여진 것이라고 하더라도 새로운 창작성을 더하지 아니한 정도이면 복제로 보아야 한다. 그리고 저작권법이 보호하는 것은 인간의 사상 또는 감정을 말·문자·음·색 등에 의하여 구체적으로 외부에 표현하는 창작적인 표현형식이므로, 복제권 또는 2차적저작물작성권의 침해 여부를 가리기 위하여 두 저작물 사이에 실질적 유사성이 있는가의 여부를 판단함에 있어서는 창작적인 표현형식에 해당하는 것만을 가지고 대비하여야 한다 ( 대법원 2010. 2. 11. 선고 2007다63409 판결 등 참조). 또한 저작권법이 보호하는 복제권의 침해가 있다고 하기 위하여는 침해되었다고 주장되는 기존의 저작물과 대비대상이 되는 저작물 사이에 실질적 유사성이 있다는 점 이외에도 대상 저작물이 기존의 저작물
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]
INFO | reranked results [case_only] | count=5
INFO | reranked results [case_only] #1 | case=2012도13748 | type=case_law | article=[] | preview=【주 문】상고를 기각한다. 이    유 상고이유를 판단한다. 1. 이른바 인터넷 링크(Internet link)는 인터넷에서 링크하고자 하는 웹페이지나, 웹사이트 등의 서버에 저장된 개개의 저작물 등의 웹 위치 정보나 경로를 나타낸 것에 불과하여, 비록 인터넷 이용자가 링크 부분을 클릭
INFO | reranked results [case_only] #2 | case=2017도19025 | type=case_law | article=['18', '2', '10', '136', '46', '23', '35', '50', '52', '21', '22', '32', '140', '31'] | preview=헌법재판소 2002. 4. 25. 선고 2001헌마200 결정  등 참조).  링크가 설정되면 인터넷 특성상 수많은 인터넷 이용자들이 링크를 통해 링크 대상 정보에 접근할 수 있다. 만일 링크 대상 정보가 침해 게시물이라면, 그러한 정보에 연결되는 링크를 제공하는 행위는 경우에 따라서는
INFO | reranked results [case_only] #3 | case=2017도19025 | type=case_law | article=['18', '2', '10', '136', '46', '23', '35', '50', '52', '21', '22', '32', '140', '31'] | preview=공중송신 중 전송에서 말하는 ‘공중의 구성원이 개별적으로 선택한 시간과 장소에서 접근할 수 있도록 저작물 등을 이용에 제공하는 것’의 전형적인 예로는, 공중의 구성원이 이용할 수 있는 상태로 저작물 등을 인터넷 웹사이트 서버에 업로드 하는 경우를 들 수 있다. 공중의 구성원에게 저작물
INFO | reranked results [case_only] #4 | case=2017도19025 | type=case_law | article=['18', '2', '10', '136', '46', '23', '35', '50', '52', '21', '22', '32', '140', '31'] | preview=링크는 인터넷 공간의 정보를 연결하고 공유하는 핵심적인 수단이다. 따라서 이용자들이 인터넷 공간에서 다른 정보에 대한 링크를 자유롭게 할 수 있도록 허용함으로써 표현의 자유를 보장하고 정보의 자유로운 유통을 촉진할 필요가 있다.  나. 링크의 자유의 한계  표현의 자유와 정보 유통의 자
INFO | reranked results [case_only] #5 | case=2017도19025 | type=case_law | article=['18', '2', '10', '136', '46', '23', '35', '50', '52', '21', '22', '32', '140', '31'] | preview=대법원 2013. 9. 26. 선고 2011도1435 판결  등 참조).  최근 저작재산권자의 이용허락 없이 전송되는 방송프로그램, 영화, 만화 등 침해 게시물로 연결되는 링크를 공중에게 제공하면서 배너 광고를 통해 광고 수익을 얻는 등의 방식으로 링크를 온라인상 저작권 침해물의 유통
INFO | final context | mode=case_only | chars=4502

[case_only] 평가 데이터셋 생성 완료: 10건

Batches: 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]
INFO | reranked results [case_plus_qa] | count=5
INFO | reranked results [case_plus_qa] #1 | case=98다41216 | type=case_law | article=['91', '93', '95', '97'] | preview=사건명: 손해배상(지) 법원: 대법원 선고일: 1999.05.25 사건번호: 98다41216
INFO | reranked results [case_plus_qa] #2 | case=2016다276467 | type=case_law | article=['4', '2'] | preview=사건명: 손해배상(지)[부정경쟁방지 및 영업비밀보호에 관한 법률 제2조 제1호 (카)목의 성과물 도용 부정경쟁행위의 해당 여부] 법원: 대법원 선고일: 2020.03.26 사건번호: 2016다276467
INFO | reranked results [case_plus_qa] #3 | case=2011도1435 | type=case_law | article=['102', '103', '254', '140', '136', '141'] | preview=같은 취지의 원심판단은 정당한 것으로 수긍할 수 있고, 거기에 상고이유의 주장과 같은 공소사실의 특정에 관한 법리를 오해하는 등의 위법이 없다. 3. 피고인 3, 피고인 4 주식회사, 피고인 7, 피고인 8 주식회사의 상습성에 관한 상고이유에 대하여 가. 구 저작권법 제140조 본문에서
INFO | reranked results [case_plus_qa] #4 | case=QA-20 | type=qa | article=None | preview= 답변: 연예인 사진을 허락 없이 이용하는 행위는 퍼블리시티권 침해에 해당할 수 있으니 주의해야 합니다.연예인 등 유명인의 경우에는 인격적 이익보다는 경제적 이익이 주로 문제된다고 하는 특수성이 있다는 점을 감안하여 많은 학자들이 일반적인 인격권으로서의 초상권과는 별개의 재산적 권리로서
INFO | reranked results [case_plus_qa] #5 | case=QA-20 | type=qa | article=None | preview=질문: 인터넷에 게시되어 있는 연예인 사진을 이용하였는데 퍼블리시티권 침해에 해당하는 것일까요?
INFO | final context | mode=case_plus_qa | chars=2620
INFO | final context preview | [Source 1] case_number=98다41216 | document_type=case_law | article=제91조, 제93조, 제95조, 제97조 | ho=항 정보 없음 사건명: 손해배상(지) 법원: 대법원 선고일: 1999.05.25 사건번호: 98다41216  [Source 2] case_number=2016다276467 | document_type=case_law | article=제4조, 제2조 | ho=제1항 사건명: 손해배상(지)[부정경쟁방지 및 영업비밀보호에 관한 법률 제2조 제1호 (카)목의 성과물 도용 부정경쟁행위의 해당 여부] 법원: 대법원 선고일: 2020.03.26 사건번호: 2016다276467  [Source 3] case_number=2011도1435 | document_type=case_law | article=제102조, 제103조, 제254조, 제140조, 제136조 | ho=제1항, 제2항, 제5항, 제4항 같은 취지의 원심판단은 정당한 것으로 수긍할 수 있고, 거기에 상고이유의 주장과 같은 공소사실의 특정에 관한 법리를 오해하는 등의 위법이 없다. 3. 피고인 3, 피고인 4 주식회사, 피고인 7, 피고인 8 주식회사의 상습성에 관한 상고이유에 대하여 가. 구 저작권법 제140조 본문에서는 저작재산권 침해로 인한 같은 법 제136조 제1항의 죄를 친고죄로 규정하면서, 같은 법 제140조 단서 제1호에서 영리를 위하여 상습적으로 위와 같은 범행을 한 경우에는 고소가 없어도 공소를 제기할 수 있다고 규정하고 있는바, 같은 법 제140조 단서 제1호가 규정한 ‘상습적으로’라고 함은 반복하여 저작권 침해행위를 하는 습벽으로서의 행위자의 속성을 말한다고 봄이 상당하고, 이러한 습벽의 유무를 판단함에 있어서는 동종 전과가 중요한 판단자료가 되나 동종 전과가 없다고 하더라도 범행의 횟수, 수단과 방법, 동기 등 제반 사정을 참작하여 저작재산권 침해행위를 하는 습벽이 인정되는 경우에는 상습성을 인정하여야 할 것이며, 한편 같은 법 제141조의 양벌규정의 적용에 있어서는 행위자인 법인의 대표자나 법인 또는 개인의 대리인·사용인 그 밖의 종업원의 위와 같은 습벽 유무에 따라 친고죄인지 여부를 판단하여야 할 것이다( 대법원 2011. 9. 8. 선고 2010도14475 판결 등 참조). 나. 제1심 및 원심이 적법하게 조사하여 채택한 증거들에 의하면 다음과 같은 사정들을 알 수 있다.  [Source 4] case_number=QA-20 | document_type=qa | article=조문 정보 없음 | ho=항 정보 없음  답변: 연예인 사진을 허락 없이 이용하는 행위는 퍼블리시티권 침해에 해당할 수 있으니 주의해야 합니다.연예인 등 유명인의 경우에는 인격적 이익보다는 경제적 이익이 주로 문제된다고 하는 특수성이 있다는 점을 감안하여 많은 학자들이 일반적인 인격권으로서의 초상권과는 별개의 재산적 권리로서 이른바 ‘퍼블리시티권’ 을 인정해야 한다고 주장하고 있습니다. 고유의 명성, 사회적 평가, 지명도
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]
INFO | reranked results [case_plus_qa] | count=5
INFO | reranked results [case_plus_qa] #1 | case=2012다73493,73509 | type=case_law | article=None | preview=【주 문】상고를 기각한다.  상고비용은 피고(반소원고)가 부담한다. 이    유 상고이유를 판단한다. 1. 상고이유 제1점 및 제2점에 대하여 다른 사람의 저작물을 무단히 복제하게 되면 복제권의 침해가 되고 이 경우 저작물을 원형 그대로 복제하지 아니하고 다소의 수정·증감이나 변경이 가
INFO | reranked results [case_plus_qa] #2 | case=2010다79923 | type=case_law | article=['13', '26', '47'] | preview=【주 문】상고를 모두 기각한다.  상고비용은 원고들이 부담한다. 이    유 상고이유를 판단한다. 1. 저작자는 그의 저작물의 내용·형식 및 제호의 동일성을 유지할 권리를 가지는데( 저작권법 제13조 제1항 ), 저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경한 경우에
INFO | reranked results [case_plus_qa] #3 | case=2011도3599 | type=case_law | article=['5'] | preview= 상고이유를 판단한다. 1. 저작권법 제5조 제1항은 ‘원저작물을 번역·편곡·변형·각색·영상제작 그 밖의 방법으로 작성한 창작물’을 ‘2차적저작물’이라고 규정하고 있는바, 2차적저작물이 되기 위해서는 원저작물을 기초로 수정·증감이 가해지되 원저작물과 실질적 유사성을 유지하여야 한다. 따
INFO | reranked results [case_plus_qa] #4 | case=QA-19 | type=qa | article=['16', '28', '26', '29', '32', '34', '35'] | preview=질문: 리포트나 논문의 작성 시 다른 어문저작물을 인용한 경우에도 저작권 침해의 문제가 발생할 수 있을까요?
INFO | reranked results [case_plus_qa] #5 | case=QA-17 | type=qa | article=['2', '7'] | preview= 답변: 신문기자의 창작성이 반영된 일반적인 신문기사를 그대로 이용하였다면 저작권 침해에 해당할 수 있습니다.저작권법에서 보호하는 저작물은 ‘인간의 사상 또는 감정을 표현한 창작물’ 을 의미합니다(저작권법 제2조 제1호). ​대부분의 기사의 경우 기자의 사상과 감정이 표현되어, 창작성이
INFO | final context | mode=case_plus_qa | chars=8597
INFO | final context preview | [Source 1] case_number=2012다73493,73509 | document_type=case_law | article=조문 정보 없음 | ho=항 정보 없음 【주 문】상고를 기각한다.  상고비용은 피고(반소원고)가 부담한다. 이    유 상고이유를 판단한다. 1. 상고이유 제1점 및 제2점에 대하여 다른 사람의 저작물을 무단히 복제하게 되면 복제권의 침해가 되고 이 경우 저작물을 원형 그대로 복제하지 아니하고 다소의 수정·증감이나 변경이 가하여진 것이라고 하더라도 새로운 창작성을 더하지 아니한 정도이면 복제로 보아야 한다. 그리고 저작권법이 보호하는 것은 인간의 사상 또는 감정을 말·문자·음·색 등에 의하여 구체적으로 외부에 표현하는 창작적인 표현형식이므로, 복제권 또는 2차적저작물작성권의 침해 여부를 가리기 위하여 두 저작물 사이에 실질적 유사성이 있는가의 여부를 판단함에 있어서는 창작적인 표현형식에 해당하는 것만을 가지고 대비하여야 한다 ( 대법원 2010. 2. 11. 선고 2007다63409 판결 등 참조). 또한 저작권법이 보호하는 복제권의 침해가 있다고 하기 위하여는 침해되었다고 주장되는 기존의 저작물과 대비대상이 되는 저작물 사이에 실질적 유사성이 있다는 점 이외에도 대상 저작물이 기존의 저작물에 의거하여 작성되었다는 점이 인정되어야 한다. 이때 대상 저작물이 기존의 저작물에 의거하여 작성되었다는 사실이 직접 인정되지 아니하더라도 기존의 저작물에 대한 접근가능성, 대상 저작물과 기존의 저작물 사이에 실질적 유사성 등의 간접사실이 인정되면 대상 저작물이 기존의 저작물에 의거하여 작성되었다는 점은 사실상 추정된다 ( 대법원 2007. 12. 13. 선고 2005다35707 판결 참조). 그리고 대상 저작물이 기존의 저작물에 의거하여 작성되었는지 여부와 양 저작물 사이에 실질적 유사성이 있는지 여부는 서로 별개의 판단으로서, 전자의 판단에는 후자의 판단과 달리 저작권법에 의하여 보호받는 표현뿐만 아니라 저작권법에 의하여 보호받지 못하는 표현 등이 유사한지 여부도 함께 참작될 수 있다 ( 대법원 2007. 3. 29. 선고 2005다44138 판결 참조).  [Source 2] case_number=2010다79923 | document_type=case_law | article=제13조, 제26조, 제47조 | ho=제1항, 제6항 【주 문】상고를 모두 기각한다.  상고비용은 원고들이 부담한다. 이    유 상고이유를 판단한다. 1. 저작자는 그의 저작물의 내용·형식 및 제호의 동일성을 유지할 권리를 가지는데( 저작권법 제13조 제1항 ), 저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경한 경우에는 저작자의 위와 같은 동일성유지권 침해에 해당하지 아니한다 ( 대법원 1992. 12. 24. 선고 92다31309 판결 등 참조). 그리고 저작물에 대한 출판계약을 체결한 저작자가 저작물의 변경에 대하여 동의하였는지 여부 및 동의의 범위는 출판계약의 성질·체결 경위·내용, 계약 당사자들의 지위와 상호관
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]
INFO | reranked results [case_plus_qa] | count=5
INFO | reranked results [case_plus_qa] #1 | case=2012도10777 | type=case_law | article=['25'] | preview= 상고이유를 판단한다. 1. 원심은, 피고인들이 2002년 한·일월드컵 당시 널리 사용된 “Be The Reds!”라는 응원문구를 도안화한 원심 판시 저작물 (이하 ‘이 사건 저작물’이라 한다)이 그려진 티셔츠 등을 착용한 모델을 촬영한 원심 판시 사진들(이하 ‘이 사건 사진들’이라 한
INFO | reranked results [case_plus_qa] #2 | case=2012도10786 | type=case_law | article=['28'] | preview= 상고이유를 판단한다. 1. 원심은, 인터넷상에서 사진의 양도·이용허락을 중개하는 이른바 포토라이브러리(photo library)업을 영위하는 피고인들이 2002년 한·일월드컵 당시 널리 사용된 “Be The Reds!”라는 응원문구를 도안화한 원심 판시 저작물 (이하, ‘이 사건 저작
INFO | reranked results [case_plus_qa] #3 | case=2010다103185 | type=case_law | article=['10', '35'] | preview= 상고이유(제출기간 경과 후에 제출된 상고이유보충서의 기재는 상고이유를 보충하는 범위 내에서)를 함께 판단한다. 1. 사람은 누구나 자신의 얼굴 기타 사회통념상 특정인임을 식별할 수 있는 신체적 특징에 관하여 함부로 촬영 또는 그림묘사되거나 공표되지 아니하며 영리적으로 이용당하지 않을
INFO | reranked results [case_plus_qa] #4 | case=QA-20 | type=qa | article=None | preview=질문: 인터넷에 게시되어 있는 연예인 사진을 이용하였는데 퍼블리시티권 침해에 해당하는 것일까요?
INFO | reranked results [case_plus_qa] #5 | case=QA-20 | type=qa | article=None | preview= 답변: 연예인 사진을 허락 없이 이용하는 행위는 퍼블리시티권 침해에 해당할 수 있으니 주의해야 합니다.연예인 등 유명인의 경우에는 인격적 이익보다는 경제적 이익이 주로 문제된다고 하는 특수성이 있다는 점을 감안하여 많은 학자들이 일반적인 인격권으로서의 초상권과는 별개의 재산적 권리로서
INFO | final context | mode=case_plus_qa | chars=12093
INFO | final context preview | [Source 1] case_number=2012도10777 | document_type=case_law | article=제25조 | ho=항 정보 없음  상고이유를 판단한다. 1. 원심은, 피고인들이 2002년 한·일월드컵 당시 널리 사용된 “Be The Reds!”라는 응원문구를 도안화한 원심 판시 저작물 (이하 ‘이 사건 저작물’이라 한다)이 그려진 티셔츠 등을 착용한 모델을 촬영한 원심 판시 사진들(이하 ‘이 사건 사진들’이라 한다)을 인터넷 상에서 양도·이용허락을 중개하는 이른바 포토라이브러리(photo library) 업체에 위탁하면서 배포한 것이 저작권침해에 해당하지 아니한다고 판단하였는바, 그 요지는, 이 사건 저작물은 그 소재인 응원문구의 호소력, 국민들의 집단적인 응원활동이라는 사회적·문화적 배경, 그 상업적·기능적인 성격 등에 비추어 보호범위가 제한적이고, 이 사건 사진들에서 차지하는 위치, 크기, 비중 등에 비추어 볼 때 간접적·부수적으로 이용한 것에 불과하며, 이 사건 사진들에서 이 사건 저작물의 창작적인 표현형식을 직접 감득하기 곤란할 뿐만 아니라 이 사건 사진들이 이 사건 저작물의 저작권자가 영위하던 상품화 사업을 직접 침해하지도 아니하였다는 것이다. 2. 원심의 판단은 결국 이 사건 사진들은 이 사건 저작물과 실질적 유사성이 인정되지 아니하거나, 피고인들이 이 사건 저작물이 표현되어 있는 이 사건 사진들을 배포한 것은 구 저작권법(2006. 12. 28. 법률 제8101호로 개정되기 이전의 것, 이하 같다) 제25조가 규정한 공표된 저작물의 인용에 해당한다는 것으로 요약된다. 그러나 원심의 위와 같은 판단은 다음과 같은 이유로 수긍하기 어렵다. 가. 우선, 이 사건 사진들과 이 사건 저작물 사이의 실질적 유사성에 관하여 살펴본다. (1) 사진촬영이나 녹화 등의 과정에서 원저작물이 그대로 복제된 경우, 새로운 저작물의 성질, 내용, 전체적인 구도 등에 비추어 볼 때, 원저작물이 새로운 저작물 속에서 주된 표현력을 발휘하는 대상물의 사진촬영이나 녹화 등에 종속적으로 수반되거나 우연히 배경으로 포함되는 경우 등과 같이 부수적으로 이용되어 그 양적·질적 비중이나 중요성이 경미한 정도에 그치는 것이 아니라 새로운 저작물에서 원저작물의 창작적인 표현형식이 그대로 느껴진다면 이들 사이에 실질적 유사성이 있다고 보아야 한다. (2) 위 법리와 원심이 적법하게 채택한 증거에 의하여 살펴본다. 이 사건 저작물은 “Be The Reds!”라는 2002년 한·일월드컵 당시 널리 알려진 응원문구를 소재로 한 것으로서, 그 창조적 개성은 전통적인 붓글씨체를 사용하여 역동적이고 생동감 있는 응원의 느낌을 표현하고 있는 도안 자체에 있다. 그런데 이 사건 사진들 중 일부 사진들(이하 ‘이 사건 침해사진들’이라 한다)에는 이 사건 저작물의 원래 모습이 온전히 또는 대부분 인식이 가능한 크기와 형태로 사진의 중심부에 위치하여 그 창조적 개성이 그대로 옮겨져 있다. 또한 이 사건 저작물의 위와 같은 창작적 요소에 담겨 있는 월드컵 응원문화에
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.27s/it]
INFO | reranked results [case_plus_qa] | count=5
INFO | reranked results [case_plus_qa] #1 | case=2006도4126 | type=case_law | article=[] | preview=【주 문】원심판결을 파기하고, 사건을 서울중앙지방법원 합의부에 환송한다. 이    유 상고이유를 본다. 원심은 그 판시와 같은 사실을 인정한 다음,          공소외인과          피고인 1 사이의 1996. 6. 26.자 이 사건 합의서 제3항에서 원심 판시 이 사건 기존
INFO | reranked results [case_plus_qa] #2 | case=97후860,877,884 | type=case_law | article=['7', '12', '96', '14'] | preview=에 해당한다고 봄이 상당하다  .  그리고  이러한 경우에 그 저명한 화가가 생존해 있었더라면 자신의 저작물임을 나타내기 위하여 표시해 오던 서명을 타인이 자신과 전혀 무관한 상품의 상표로 무단 등록하여 공표하고 사용하는 것은 저명한 미술저작자로서의 인격권을 침해하는 불법행위에 해당한다
INFO | reranked results [case_plus_qa] #3 | case=70누39 | type=case_law | article=['11', '17', '18', '13'] | preview=사건명: 상영허가취소 법원: 대법원 선고일: 1970.06.30 사건번호: 70누39  판례내용: 원고 소송대리인 변호사 조승각의 상고이유를 판단한다.영화법 제11조 제1항과 같은법 시행령 제17조 제1항에 의하면 영화를 제작하고자 하는 자는 그 제작할 영화의 대본과 그 대본을 저작한
INFO | reranked results [case_plus_qa] #4 | case=QA-5 | type=qa | article=[] | preview=질문: 갑은 의류업 종사자인데 이미 사망한 유명인의 초상을 이용하여 티셔츠를 만들어서 팔고자 하는 바, 이 경우 법률상 문제가 발생할 수 있는지요? 답변: 판례의 입장은 통일되지 아니한 상태이므로 상속인의 허락을 얻는 것이 안전합니다. 초상권은 판례를 통해 인정되어 온 권리로, 그 권리
INFO | reranked results [case_plus_qa] #5 | case=QA-20 | type=qa | article=None | preview= 답변: 연예인 사진을 허락 없이 이용하는 행위는 퍼블리시티권 침해에 해당할 수 있으니 주의해야 합니다.연예인 등 유명인의 경우에는 인격적 이익보다는 경제적 이익이 주로 문제된다고 하는 특수성이 있다는 점을 감안하여 많은 학자들이 일반적인 인격권으로서의 초상권과는 별개의 재산적 권리로서
INFO | final context | mode=case_plus_qa | chars=4777
INFO | final context preview | [Source 1] case_number=2006도4126 | document_type=case_law | article=조문 정보 없음 | ho=제3항 【주 문】원심판결을 파기하고, 사건을 서울중앙지방법원 합의부에 환송한다. 이    유 상고이유를 본다. 원심은 그 판시와 같은 사실을 인정한 다음,          공소외인과          피고인 1 사이의 1996. 6. 26.자 이 사건 합의서 제3항에서 원심 판시 이 사건 기존 4개 음반에 수록된 음원을 이용하여 이 사건 기존 4개 음반 및 라이브 음반 이외의 새로운 음반을 제작할 경우에는          공소외인과          피고인 1의 합의하에 계약을 체결하기로 약정하였음을 근거로, 이 사건 기존 4개 음반에 대하여 사망한 가수 김광석이 가지고 있던 실연자로서의 저작인접권이 김광석의 아버지          공소외인과 처인          피고인 1의 공유라고 판단하였다. 그러나 이 사건 합의서에 의하면, 이 사건 합의서 제3항에서 정하고 있는 것은 이 사건 기존 4개 음반에 수록된 음원을 이용하여 제작될 새로운 음반에 관한 것이지, 그 음원 자체에 관한 것이 아니고, 이 사건 합의서 제3항에서는 이 사건 기존 4개 음반에 수록된 음원을 이용하여 제작될 새로운 음반에 관한 것 이외에 저작인접권의 행사 태양에 대하여는 정하고 있지 않으므로, 이 사건 합의서 제3항이 이 사건 기존 4개 음반에 대하여 김광석이 가지고 있던 실연자로서의 저작인접권 자체를          공소외인과          피고인 1의 공유로 하기로 하는 합의라고 볼 수는 없으며, 이는 원심이 참작한 다른 사정을 고려하더라도 마찬가지이다. 한편, 이 사건 합의서 제1, 2항도 같은 음원을 이용한 음반의 발매 형태별로 그 권리의 귀속자를 달리하고 있어서, 위 조항들이 발매 형태별로 권리의 귀속자를 달리할 수 없는 저작인접권의 귀속에 대하여 정한 것이라고는 볼 수 없으므로, 위 조항들은 이 사건 기존 4개 음반의 판매로부터 수익을 얻을 권리는          공소외인이, 이 사건 기존 4개 음반에 수록된 음원을 이용하여  [Source 2] case_number=97후860,877,884 | document_type=case_law | article=제7조, 제12조, 제96조, 제14조 | ho=제1항, 제2항 에 해당한다고 봄이 상당하다  .  그리고  이러한 경우에 그 저명한 화가가 생존해 있었더라면 자신의 저작물임을 나타내기 위하여 표시해 오던 서명을 타인이 자신과 전혀 무관한 상품의 상표로 무단 등록하여 공표하고 사용하는 것은 저명한 미술저작자로서의 인격권을 침해하는 불법행위에 해당한다 할 것이고,  저작권법 제96조  , 제14조 제2항  에 의하면 사망한 저작자의 저작인격권을 침해하는 행위에 대하여 그 저작자의 유족이 그 침해행위의 금지를 청구하는 등의 조치를 취할 수 있음에 비추어, 그 저명한 화가의 유족으로서는 고인의 인격권과 유족 자신의 고인에 대한 추모경애의 마음을 침해하는 상표의 사용금지
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]
INFO | reranked results [case_plus_qa] | count=5
INFO | reranked results [case_plus_qa] #1 | case=2010다79923 | type=case_law | article=['13', '26', '47'] | preview=【주 문】상고를 모두 기각한다.  상고비용은 원고들이 부담한다. 이    유 상고이유를 판단한다. 1. 저작자는 그의 저작물의 내용·형식 및 제호의 동일성을 유지할 권리를 가지는데( 저작권법 제13조 제1항 ), 저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경한 경우에
INFO | reranked results [case_plus_qa] #2 | case=2007다63409 | type=case_law | article=['5'] | preview=소정의 2차적저작물로 보호받기 위하여는 원저작물을 기초로 하되 원저작물과 실질적 유사성을 유지하고 이것에 사회통념상 새로운 저작물이 될 수 있을 정도의 수정·증감을 가하여 새로운 창작성을 부가하여야 하는 것이므로 ( 대법원 2002. 1. 25. 선고 99도863 판결 , 대법원 200
INFO | reranked results [case_plus_qa] #3 | case=94마2217 | type=case_law | article=['14'] | preview=그러나.  저작인격권은 저작재산권과는 달리 일신전속적인 권리로서 이를 양도하거나 이전할 수 없는 것이라 할 것이므로 비록 그 권한행사에 있어서는 이를 대리하거나 위임하는 것이 가능하다 할지라도 이는 어디까지나 저작인격권의 본질을 해하지 아니하는 한도 내에서만 가능하다 할 것이고 저작인격
INFO | reranked results [case_plus_qa] #4 | case=QA-3 | type=qa | article=['9', '2', '10', '14', '45', '13', '11', '46', '12', '22'] | preview=아울러 乙은 같은 법 제12조 제1항에 규정된 성명표시권 침해 주장을 해볼 수 있으나, 사안의 경우 마스코트에는 통상적으로 저작자의 성명이 표시되지 않는 것이 일반적이라 할 것이므로 乙의 이름이 표시되지 않았다고 하더라도 성명표시권 침해 주장을 하기는 역시 어려워 보입니다(같은 법 제1
INFO | reranked results [case_plus_qa] #5 | case=QA-3 | type=qa | article=['9', '2', '10', '14', '45', '13', '11', '46', '12', '22'] | preview=한편, 저작재산권 양도 계약에 관하여 살펴보면, 저작재산권은 전부 또는 일부를 양도할 수 있는바(저작권법 제45조 제1항), 甲회사와 乙은 제작된 도안에 대한 소유권과 저작권 등 모든 권리를 가짐은 물론 수정요구까지 할 수 있다는 내용의 캐릭터제작계약을 체결하였으므로 저작재산권은 甲에게
INFO | final context | mode=case_plus_qa | chars=4143
INFO | final context preview | [Source 1] case_number=2010다79923 | document_type=case_law | article=제13조, 제26조, 제47조 | ho=제1항, 제6항 【주 문】상고를 모두 기각한다.  상고비용은 원고들이 부담한다. 이    유 상고이유를 판단한다. 1. 저작자는 그의 저작물의 내용·형식 및 제호의 동일성을 유지할 권리를 가지는데( 저작권법 제13조 제1항 ), 저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경한 경우에는 저작자의 위와 같은 동일성유지권 침해에 해당하지 아니한다 ( 대법원 1992. 12. 24. 선고 92다31309 판결 등 참조). 그리고 저작물에 대한 출판계약을 체결한 저작자가 저작물의 변경에 대하여 동의하였는지 여부 및 동의의 범위는 출판계약의 성질·체결 경위·내용, 계약 당사자들의 지위와 상호관계, 출판의 목적, 출판물의 이용실태, 저작물의 성격 등 제반 사정을 종합적으로 고려하여 구체적·개별적으로 판단하여야 한다. 한편 행정처분이 아무리 위법하다고 하여도 그 하자가 중대하고 명백하여 당연 무효라고 보아야 할 사유가 있는 경우를 제외하고는 아무도 그 하자를 이유로 무단히 그 효과를 부정하지 못하는 것이므로 ( 대법원 2010. 4. 29. 선고 2007다12012 판결 등 참조), 저작자가 출판계약에서 행정처분을 따르는 범위 내에서의 저작물 변경에 동의한 경우에는, 설사 행정처분이 위법하더라도 당연 무효라고 보아야 할 사유가 있다고 할 수 없는 이상 그 행정처분에 따른 계약 상대방의 저작물 변경은 저작자의 동일성유지권 침해에 해당하지 아니한다. 2. 위 법리에 비추어 살펴본다. 가. 원심판결 이유와 기록에 의하면, 다음과 같은 사실들을 알 수 있다.  [Source 2] case_number=2007다63409 | document_type=case_law | article=제5조 | ho=제1항 소정의 2차적저작물로 보호받기 위하여는 원저작물을 기초로 하되 원저작물과 실질적 유사성을 유지하고 이것에 사회통념상 새로운 저작물이 될 수 있을 정도의 수정·증감을 가하여 새로운 창작성을 부가하여야 하는 것이므로 ( 대법원 2002. 1. 25. 선고 99도863 판결 , 대법원 2004. 7. 8. 선고 2004다18736 판결 등 참조), 어떤 저작물이 기존의 저작물을 다소 이용하였더라도 기존의 저작물과 실질적인 유사성이 없는 별개의 독립적인 신 저작물이 되었다면, 이는 창작으로서 기존의 저작물의 저작권을 침해한 것이 되지 아니한다. 그리고 저작권법이 보호하는 것은 인간의 사상 또는 감정을 말·문자·음·색 등에 의하여 구체적으로 외부에 표현하는 창작적인 표현형식이므로, 복제권 또는 2차적저작물작성권의 침해 여부를 가리기 위하여 두 저작물 사이에 실질적 유사성이 있는가의 여부를 판단함에 있어서는 창작적인 표현형식에 해당하는 것만을 가지고 대비하여야 한다 ( 대법원 1999. 11. 26. 선고 98다46259 판결 , 대법원 2004. 7. 8. 선고 2004다18736 판결
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]
INFO | reranked results [case_plus_qa] | count=5
INFO | reranked results [case_plus_qa] #1 | case=2012다73493,73509 | type=case_law | article=[] | preview=【주 문】상고를 기각한다.  상고비용은 피고(반소원고)가 부담한다. 이    유 상고이유를 판단한다. 1. 상고이유 제1점 및 제2점에 대하여 다른 사람의 저작물을 무단히 복제하게 되면 복제권의 침해가 되고 이 경우 저작물을 원형 그대로 복제하지 아니하고 다소의 수정·증감이나 변경이 가
INFO | reranked results [case_plus_qa] #2 | case=94마2217 | type=case_law | article=['14'] | preview=그러나.  저작인격권은 저작재산권과는 달리 일신전속적인 권리로서 이를 양도하거나 이전할 수 없는 것이라 할 것이므로 비록 그 권한행사에 있어서는 이를 대리하거나 위임하는 것이 가능하다 할지라도 이는 어디까지나 저작인격권의 본질을 해하지 아니하는 한도 내에서만 가능하다 할 것이고 저작인격
INFO | reranked results [case_plus_qa] #3 | case=2007다63409 | type=case_law | article=['5'] | preview=소정의 2차적저작물로 보호받기 위하여는 원저작물을 기초로 하되 원저작물과 실질적 유사성을 유지하고 이것에 사회통념상 새로운 저작물이 될 수 있을 정도의 수정·증감을 가하여 새로운 창작성을 부가하여야 하는 것이므로 ( 대법원 2002. 1. 25. 선고 99도863 판결 , 대법원 200
INFO | reranked results [case_plus_qa] #4 | case=QA-16 | type=qa | article=None | preview=질문: 책이나 영화의 제목, 단체의 명칭, 짧은 슬로건이나 표어, 명언 등을 이용하는 경우에도 저작권 침해의 문제가 발생할 수 있나요?
INFO | reranked results [case_plus_qa] #5 | case=QA-19 | type=qa | article=['16', '28', '26', '29', '32', '34', '35'] | preview=질문: 리포트나 논문의 작성 시 다른 어문저작물을 인용한 경우에도 저작권 침해의 문제가 발생할 수 있을까요?
INFO | final context | mode=case_plus_qa | chars=3047
INFO | final context preview | [Source 1] case_number=2012다73493,73509 | document_type=case_law | article=조문 정보 없음 | ho=항 정보 없음 【주 문】상고를 기각한다.  상고비용은 피고(반소원고)가 부담한다. 이    유 상고이유를 판단한다. 1. 상고이유 제1점 및 제2점에 대하여 다른 사람의 저작물을 무단히 복제하게 되면 복제권의 침해가 되고 이 경우 저작물을 원형 그대로 복제하지 아니하고 다소의 수정·증감이나 변경이 가하여진 것이라고 하더라도 새로운 창작성을 더하지 아니한 정도이면 복제로 보아야 한다. 그리고 저작권법이 보호하는 것은 인간의 사상 또는 감정을 말·문자·음·색 등에 의하여 구체적으로 외부에 표현하는 창작적인 표현형식이므로, 복제권 또는 2차적저작물작성권의 침해 여부를 가리기 위하여 두 저작물 사이에 실질적 유사성이 있는가의 여부를 판단함에 있어서는 창작적인 표현형식에 해당하는 것만을 가지고 대비하여야 한다 ( 대법원 2010. 2. 11. 선고 2007다63409 판결 등 참조). 또한 저작권법이 보호하는 복제권의 침해가 있다고 하기 위하여는 침해되었다고 주장되는 기존의 저작물과 대비대상이 되는 저작물 사이에 실질적 유사성이 있다는 점 이외에도 대상 저작물이 기존의 저작물에 의거하여 작성되었다는 점이 인정되어야 한다. 이때 대상 저작물이 기존의 저작물에 의거하여 작성되었다는 사실이 직접 인정되지 아니하더라도 기존의 저작물에 대한 접근가능성, 대상 저작물과 기존의 저작물 사이에 실질적 유사성 등의 간접사실이 인정되면 대상 저작물이 기존의 저작물에 의거하여 작성되었다는 점은 사실상 추정된다 ( 대법원 2007. 12. 13. 선고 2005다35707 판결 참조). 그리고 대상 저작물이 기존의 저작물에 의거하여 작성되었는지 여부와 양 저작물 사이에 실질적 유사성이 있는지 여부는 서로 별개의 판단으로서, 전자의 판단에는 후자의 판단과 달리 저작권법에 의하여 보호받는 표현뿐만 아니라 저작권법에 의하여 보호받지 못하는 표현 등이 유사한지 여부도 함께 참작될 수 있다 ( 대법원 2007. 3. 29. 선고 2005다44138 판결 참조).  [Source 2] case_number=94마2217 | document_type=case_law | article=제14조 | ho=항 정보 없음 그러나.  저작인격권은 저작재산권과는 달리 일신전속적인 권리로서 이를 양도하거나 이전할 수 없는 것이라 할 것이므로 비록 그 권한행사에 있어서는 이를 대리하거나 위임하는 것이 가능하다 할지라도 이는 어디까지나 저작인격권의 본질을 해하지 아니하는 한도 내에서만 가능하다 할 것이고 저작인격권 자체는 저작권자에게 여전히 귀속되어 있는 것이라고 보아야 할 것이며,  구 저작권법(1986.12.31. 법률 제3916호로 전문 개정되기 전의 것, 이하 같다) 제14조  에 의하면 저작자는 자기의 저작물에 관하여 그 저작자임을 주장할 수 있는 권리(소위 귀속권)가 있으므로 타인이 무단으로 자기의 저작물에 관한 저작자의 성명,
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.27s/it]
INFO | reranked results [case_plus_qa] | count=5
INFO | reranked results [case_plus_qa] #1 | case=2012도13748 | type=case_law | article=[] | preview=【주 문】상고를 기각한다. 이    유 상고이유를 판단한다. 1. 이른바 인터넷 링크(Internet link)는 인터넷에서 링크하고자 하는 웹페이지나, 웹사이트 등의 서버에 저장된 개개의 저작물 등의 웹 위치 정보나 경로를 나타낸 것에 불과하여, 비록 인터넷 이용자가 링크 부분을 클릭
INFO | reranked results [case_plus_qa] #2 | case=2017도19025 | type=case_law | article=['18', '2', '10', '136', '46', '23', '35', '50', '52', '21', '22', '32', '140', '31'] | preview=헌법재판소 2002. 4. 25. 선고 2001헌마200 결정  등 참조).  링크가 설정되면 인터넷 특성상 수많은 인터넷 이용자들이 링크를 통해 링크 대상 정보에 접근할 수 있다. 만일 링크 대상 정보가 침해 게시물이라면, 그러한 정보에 연결되는 링크를 제공하는 행위는 경우에 따라서는
INFO | reranked results [case_plus_qa] #3 | case=2017도19025 | type=case_law | article=['18', '2', '10', '136', '46', '23', '35', '50', '52', '21', '22', '32', '140', '31'] | preview=링크는 인터넷 공간의 정보를 연결하고 공유하는 핵심적인 수단이다. 따라서 이용자들이 인터넷 공간에서 다른 정보에 대한 링크를 자유롭게 할 수 있도록 허용함으로써 표현의 자유를 보장하고 정보의 자유로운 유통을 촉진할 필요가 있다.  나. 링크의 자유의 한계  표현의 자유와 정보 유통의 자
INFO | reranked results [case_plus_qa] #4 | case=QA-7 | type=qa | article=None | preview=질문: 갑은 특정식당을 이용하고 그 이용후기로 식당에 대한 평가와 사진등을 홈페이지에 게시하였는데 을이 출처를 기재하지 않은 채 평가내용과 사진등의 정보를 무단으로 자신의 홈페이지등에 게재한 경우 저작권 침해등을 이유로 법적 재재가 가능한지요? 답변: 일반적으로 홈페이지를 통하여 인터넷
INFO | reranked results [case_plus_qa] #5 | case=QA-19 | type=qa | article=['16', '28', '26', '29', '32', '34', '35'] | preview=질문: 리포트나 논문의 작성 시 다른 어문저작물을 인용한 경우에도 저작권 침해의 문제가 발생할 수 있을까요?
INFO | final context | mode=case_plus_qa | chars=4066

[case_plus_qa] 평가 데이터셋 생성 완료: 10건

In [28]:
evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4o-mini", temperature=0))

ragas_results = {}
ragas_frames = {}
for mode, dataset in evaluation_datasets.items():
    ragas_results[mode] = evaluate(
        dataset=dataset,
        metrics=[LLMContextRecall(), Faithfulness(), FactualCorrectness()],
        llm=evaluator_llm,
    )
    ragas_frames[mode] = ragas_results[mode].to_pandas()

ragas_frames[ACTIVE_MODE].head()

/var/folders/5b/_vr668qd1qjfth5qbkggmk0m0000gn/T/ipykernel_52576/157828713.py:1: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4o-mini", temperature=0))
Evaluating: 100%|██████████| 30/30 [01:14<00:00,  2.49s/it]
Evaluating: 100%|██████████| 30/30 [01:09<00:00,  2.32s/it]

,user_input,retrieved_contexts,response,reference,context_recall,faithfulness,factual_correctness(mode=f1)
0,"연예인의 이름을 상업적 행위에 이용할 경우, 손해배상책임을 지나요?",[사건명: 손해배상(지)\n법원: 대법원\n선고일: 1999.05.25\n사건번호:...,- **핵심 답변** \n 연예인의 **이름(성명)이나 초상**을 **상업적(영...,유명 연예인이나 운동선수 등은 자신의 성명이나 초상을 상업적으로 이용할 수 있는 권...,1.000,1.000000,0.18
1,다른 사람이 나의 저작물을 패러디하였는데 저작권 침해에 해당하는 것일까요?,[【주 문】상고를 기각한다. 상고비용은 피고(반소원고)가 부담한다.\n이 유...,- 핵심 답변 \n참고 문맥만으로는 “패러디”가 저작권(복제권 또는 2차적저작물작...,"저작권법상 허용되는 패러디에 대한 판단 기준이 명확하지는 않으나, 기존의 저작물에 ...",1.000,0.818182,0.38
2,사진이나 영상에 연예인의 유행어를 이용하는 것도 침해에 해당하는 것일까요?,"[\n상고이유를 판단한다. 1. 원심은, 피고인들이 2002년 한·일월드컵 당시 널...",- 핵심 답변 \n참고 문맥에는 “연예인의 유행어”를 사진·영상에 이용하는 경우가...,짧은 유행어를 이용하는 경우는 저작권 침해로 보기는 어렵지만 퍼블리시티권 침해에 해...,1.000,0.500000,0.14
3,"이미 사망한 유명인을 모델로 하여 영화나 드라마를 제작하려고 하는데, 유족의 허락을...","[【주 문】원심판결을 파기하고, 사건을 서울중앙지방법원 합의부에 환송한다.\n이 ...",- 핵심 답변 \n판례의 입장이 통일되지 않아 **유족(상속인)의 허락을 얻는 것...,사망한 유명인의 초상이나 성명을 상업적으로 이용하는 것은 퍼블리시티권과 관련하여 법...,0.875,1.000000,0.57
4,저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경할 경우 동일성유지...,[【주 문】상고를 모두 기각한다. 상고비용은 원고들이 부담한다.\n이 유\n...,- 핵심 답변 \n아니요. 저작자가 **명시적 또는 묵시적으로 동의한 범위 내에서...,저작자가 명시적으로 동의한 범위 내에서 저작물을 변경하는 것은 아무런 문제가 되지 ...,0.800,1.000000,0.27

In [29]:
metric_columns = ["context_recall", "faithfulness", "factual_correctness(mode=f1)"]

comparison_rows = []
for mode, ragas_df in ragas_frames.items():
    available_metric_columns = [col for col in metric_columns if col in ragas_df.columns]
    ragas_summary = ragas_df[available_metric_columns].mean()
    row = {"mode": mode}
    row.update({metric: ragas_summary.get(metric) for metric in available_metric_columns})
    comparison_rows.append(row)

comparison_df = pd.DataFrame(comparison_rows)
comparison_df

           mode  context_recall  faithfulness  factual_correctness(mode=f1)
0     case_only        0.832218      0.458333                         0.198
1  case_plus_qa        0.927500      0.509596                         0.189

In [30]:
mode_to_inspect = ACTIVE_MODE
ragas_frames[mode_to_inspect][["user_input", *[col for col in metric_columns if col in ragas_frames[mode_to_inspect].columns]]].head(eval_sample_size)

,user_input,context_recall,faithfulness,factual_correctness(mode=f1)
0,"연예인의 이름을 상업적 행위에 이용할 경우, 손해배상책임을 지나요?",1.000,1.000000,0.18
1,다른 사람이 나의 저작물을 패러디하였는데 저작권 침해에 해당하는 것일까요?,1.000,0.818182,0.38
2,사진이나 영상에 연예인의 유행어를 이용하는 것도 침해에 해당하는 것일까요?,1.000,0.500000,0.14
3,"이미 사망한 유명인을 모델로 하여 영화나 드라마를 제작하려고 하는데, 유족의 허락을...",0.875,1.000000,0.57
4,저작자가 명시적 또는 묵시적으로 동의한 범위 내에서 저작물을 변경할 경우 동일성유지...,0.800,1.000000,0.27
5,다른 사람의 저작물의 제호를 수정하여 사용할 경우 저작권 침해인가요?,1.000,0.000000,0.00
6,인터넷상에서 링크를 제공하는 것도 저작권법 위반에 해당하나요?,1.000,0.777778,0.35
7,저의 사진이 저작권 등록의 대상이 될 수 있을까요?,0.600,0.000000,0.00
8,"등록신청이 신청 서류의 하자 등으로 인하여 반려되었는데, 어떻게 하면 등록을 마무리...",1.000,0.000000,0.00
9,제가 등록신청한 저작물에 대한 등록관청의 심사 범위가 어디까지인가요?,1.000,0.000000,0.00

### RAGAS Metric Guide
- `llm_context_recall`: reference answer를 재현하는 데 필요한 정보가 retrieval context에 포함되어 있는지 평가
- `faithfulness`: 생성 답변이 retrieval context에 근거하고 있는지 평가
- `factual_correctness`: 생성 답변이 reference answer와 사실적으로 일치하는지 평가